### ISSUE TITLE
transcoding: support "grpc-status-details-bin"

### ISSUE THREAD

**Issue by lizan** [cloudendpoints/esp#204]
Seems grpc-go sends "grpc-status-details-bin" in trailers to have error details (https://github.com/grpc/grpc-go/blob/v1.4.1/transport/http2_server.go#L750). We might need to support that in transcoding.

TODO:
- Confirm what is the standard format for "grpc-status-details-bin", it is not documented in [gRPC Wire Protocol](http://www.grpc.io/docs/guides/wire.html).
- Confirm C and Java stack behavior.

**Comment by bbassingthwaite-va** [comment]
Any update on this issue? Thanks!

**Comment by lizan** [comment]
Hi Braden, sorry I'm pretty busy with other stuff recently and didn't get a chance to tackle on this yet.

@yang-g, can you confirm the status in gRPC side, C and Java stack behavior?

**Comment by godspeedchu** [comment]
gentle ping, any update? thanks a lot

**Comment by JimmyCYJ** [comment]
Sorry for the delay, I will work on this feature late this week.

**Comment by bbassingthwaite-va** [comment]
Very exciting, thanks!

**Comment by qiwzhang** [comment]
We should close it after we make ESP release with this fix.  Hope next week, we are going to make a release.

**Comment by godspeedchu** [comment]
Sorry to bother, is this released? What's the ESP version that has this change? Thanks a lot!

**Comment by JimmyCYJ** [comment]
https://github.com/cloudendpoints/esp/releases/tag/v1.13.0

**Comment by JimmyCYJ** [comment]
It is in v1.13.0 now.

**Comment by godspeedchu** [comment]
I see the code and message are propagated from grpc-status-details-bin to the response but not the error details. What is the plan to support that?

**Comment by qiwzhang** [comment]
@lizan Since "details" field is "any" type.  Users can pack any proto message to it.  If ESP doesn't have the descriptor for that message, ESP could not convert it to JSON.   How can ESP get the proto descriptor?   Can they append it in the service config?  Does our service config allow users to append any descriptor files?

**Comment by bbassingthwaite-va** [comment]
I would be fine with using BadRequest 
from:
https://github.com/googleapis/googleapis/blob/31bf8302c3077d624fe61f40efc8eb92702dc491/google/rpc/error_details.proto#L120

Or any of the messages in `error_details.proto`

**Comment by qiwzhang** [comment]
@bbassingthwaite-va Please clarify.   BadRequest  for "details" is working.   Or you will be fine if we can make it work?

**Comment by bbassingthwaite-va** [comment]
Sorry I haven't had a chance to try it, but I would have expected that I could use messages from `error_details.proto` inside of the `details` `any` field and they would be properly transcoded to json.

**Comment by qiwzhang** [comment]
@JimmyCYJ could you try it to see sending BadRequest in "details" work?  Thanks

**Comment by godspeedchu** [comment]
I'm also interested in the PreconditionFailure in the error_details.proto, it would be great if this can be supported

**Comment by JimmyCYJ** [comment]
I will try both BadRequest and PreconditionFailure in "details" and see whether it works.

**Comment by JimmyCYJ** [comment]
I did a test by returning PreconditionFailure as Status::details, and I can see that the information in PreconditionFailure is received at client side as JSON format.

**Comment by JimmyCYJ** [comment]
Here is the response received at a test client.
HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 03 Feb 2018 01:20:12 GMT
Content-Type: application/json
Connection: close

{
 "code": 5,
 "message": "Cannot find shelf 100",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
   "violations": [
    {
     "type": "violation type 1",
     "subject": "subject 1",
     "description": "description 1"
    },
    {
     "type": "violation type 2",
     "subject": "subject 2",
     "description": "description 2"
    }
   ]
  }
 ]
}

**Comment by JimmyCYJ** [comment]
I did a test using BadRequest and I works too. Here is the response received by client.

HTTP/1.1 404 Not Found
Server: nginx
Date: Sat, 03 Feb 2018 01:27:52 GMT
Content-Type: application/json
Connection: close

{
 "code": 5,
 "message": "Cannot find shelf 100",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.BadRequest",
   "fieldViolations": [
    {
     "field": "Field violation field 1",
     "description": "Field violation description 1"
    },
    {
     "field": "Field violation field 2",
     "description": "Field violation description 2"
    }
   ]
  }
 ]
}
