### ISSUE TITLE
Nginx doesn't re-resolve Kubernetes Service VIPs

### ISSUE THREAD

**Issue by zx8** [cloudendpoints/esp#224]
We have a bunch of Nginx `location` blocks as follows:

```
location /Service1/MethodA {
  grpc_pass service-1:5000 override;
}

location /Service2/MethodB {
  grpc_pass service-2:5000 override;
}

location /Service3/MethodC {
  grpc_pass service-3:5000 override;
}
```

If, for example, I were to delete and re-create the `service-3` Service in Kubernetes, it would be assigned a new VIP address, but the Pods would remain the same, resulting in "backend unavailable" errors.

Is it possible to re-resolve Service IP addresses (or obey DNS TTL) without having to restart Nginx?

**Comment by qiwzhang** [comment]
grpc channel stub is cached [here](https://github.com/cloudendpoints/esp/blob/master/src/nginx/module.h#L170)

We can put expiration on each map entry to solve this.

The issue was raised long time ago, not sure if there is such requirement.  If there is, we can fix it.
