### ISSUE TITLE
JWT validation failed: KEY_RETRIEVAL_ERROR

### ISSUE THREAD

**Issue by ghost** [cloudendpoints/esp#260]
I am using Google Cloud Endpoints with container engine.  I have set up a custom security definition to verify a JWT from Azure AD.  I have set the x-google-jwks_uri="https://login.microsoftonline.com/common/discovery/v2.0/keys".  

I receive the following error on the esp

E0906 20:02:18.843727344      11 auth_jwt_validator.cc:570]  Cannot find matching key in key set for kid=HHByKU-0DqAqMZh6ZFPd2VWaOtg and alg=RS256

This key is clearly in the keys list.  Is there anything else that could be responsible for not finding it?

**Comment by liminw** [comment]
ESP was looking for "alg" parameter in the public key and could not find it. This is why you see the error.

**Comment by lizan** [comment]
I think we should use the key if "kid" matches while there is no "alg". @liminw thoughts?

**Comment by liminw** [comment]
ESP currently does not support JWKS keys without "alg" field. But we are currently working on the fix.

**Comment by kanagunbr** [comment]
Any update on this, I have exact same problem.

**Comment by lizan** [comment]
https://github.com/cloudendpoints/esp/pull/274 already fixed the original issue, if you are using latest ESP, you shouldn't have the same problem.

**Comment by lizan** [comment]
Fixed by #274, Released as 1.9.0

**Comment by kanagunbr** [comment]
Thank you very much!. After upgrading ESP, it worked like a charm.
