### ISSUE TITLE
Allow ESP container parameters to be specified by environment variables

### ISSUE THREAD

**Issue by tonglil** [cloudendpoints/esp#284]
Reading the startup parameters via env vars (vs through flags) could help simplify configurability, especially in a container environment such as Kubernetes using ConfigMaps.

In addition, this could also allow instances of reloading the configuration dynamically instead of starting a new container when env vars change.

**Comment by qiwzhang** [comment]
ESP should be deployed as container.  For container, it should be easy to specify start up flags.   Generally, you don't re-start the container entry process.  You just re-start the container.

**Comment by tonglil** [comment]
Thanks, I think we can then configure the flag parameters from env vars using this https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config

**Comment by qiwzhang** [comment]
You can also directly pass the command arguments to esp container.  I don't see the value added by using environment variables.  I like to justify the work.
