### ISSUE TITLE
Documentation Issues?

### ISSUE THREAD

**Issue by rkdirect** [cloudendpoints/esp#296]
A couple of documentation issues I ran into when setting up a new build machine (debian/jessie)

1. The package "build-essentials" is required for libtoolize
1. The package "aclocal" is required by bazel for the command by the same name
2. The installation requirements for bazel, clang, etc are all scripted, please consider recommending users run these scripts and include instructions for running them as an alternative.

**Comment by qiwzhang** [comment]
Hi @lei-tang could you help update our README or ESP doc in this repo to reflect these requirements?
@rkdirect Thanks for these valuable info.

**Comment by lei-tang** [comment]
I will update the documents.

**Comment by lei-tang** [comment]
I will update the documents.
Regards,
Lei

**Comment by lei-tang** [comment]
The documents have been updated (commit ec40f63): 
1. Add the software packages required for building ESP.
2. Add the software packages required for running ESP tests.
3. Add a step-by-step guide for building ESP on Ubuntu 16.04, and running tests.
