### ISSUE TITLE
Transcode to HTTP/Protobuf

### ISSUE THREAD

**Issue by bourquep** [cloudendpoints/esp#317]
Is there a way to configure ESP to use binary protobuf for payloads when a gRPC service is accessed via HTTP?

In other words, instead of always transcoding protobuf to JSON when using the HTTP transcoder, stick to binary protobuf?

**Comment by qiwzhang** [comment]
To support HTTP/proto?   I think it is not supported.    @fengli79 @lizan could you confirm?

But it should be easy to add.  The code is here: https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc

We welcome contribution.

**Comment by lizan** [comment]
@bourquep What is your usecase, doesn't [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) fit it? @fengli79 added gRPC-web capability to ESP so you can use it.

**Comment by bourquep** [comment]
@lizan Thanks, I had dismissed grpc-web based on the fact that it is still very early and no official client seem to be available yet, but I'll give it a more thorough look.

**Comment by bourquep** [comment]
I'm up and running with grpc-web, thanks for the tip!
