### ISSUE TITLE
Jenkins test run out of metadata space limit

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#327]
In GCE tests,  it needs to use "gcloud compute ssh" instance, but ssh-key is not removed.  It used a lot of metadata limit of 32KB. 

We need to remove all used ssh-key in the project metadata.

**Comment by lei-tang** [comment]
The ssh keys can be seen at: https://pantheon.corp.google.com/compute/metadata/sshKeys?project=endpoints-jenkins&organizationId=433637338589

**Comment by lei-tang** [comment]
The PR for this issue is at: https://github.com/cloudendpoints/esp/pull/329.
