### ISSUE TITLE
Required properties not working as expected

### ISSUE THREAD

**Issue by Aicos** [cloudendpoints/esp#333]
Not sure if I'm posting in the write place, but I'm having a problem getting the validation to fail when it should on my esp proxy setup.  

This is basically the setup I have:
https://cloud.google.com/endpoints/docs/openapi/get-started-compute-engine

Validation successfully fails on POST routes that only contain one parameter. But not on routes that look like the following with 2 parameters:

Part of my deployment YAML:

```
  /something/{uuid}/thing:
    post: 
      description: Add a new intake
      operationId: thingPost
      parameters:
        - name: uuid
          required: true
          in: path
          type: string
        - name: meal
          in: body
          description: Meal intake record, covering macro-nutrients
          required: true
          schema: 
            $ref: '#/definitions/thing'
      responses:
        "204":
          description: Meal record succesfully received.
        default:
          description: unexpected error
  thing:
    required:
      - time_stamp
      - carb
    properties:
      time_stamp: 
        type: integer
        description: Unix Timestamp
      carb:
        type: integer
        description: Amount of carbohydrates (g) in the meal.
      fat:
        type: integer
        description: Amount of fat (g) in the meal.
      protein: 
        type: integer
        description: Amount of protein (g) in the meal.
      comment:
        type: string
        description: Free text field. Could contain, e.g., meal description. Such as \"Sandwich with milk\".        

```
I would expect to get a validation error if I miss out the time_stamp property, as that is a required property. But I don't.  

Why is this happening? Am I doing something wrong? I would post the whole YAML but I'm not really alowed to.

Thanks.

**Comment by qiwzhang** [comment]
Google cloud endpoints doesn't parse request body, hence "required" fields from the OpenAPI spec. are not verified by the proxy.   For performance reason, proxy is not the place to parse request body.

**Comment by Aicos** [comment]
So what is generating the error message on my other routes when I've missed a required field?

**Comment by qiwzhang** [comment]
I am not sure which component send the errors.   I am pretty sure cloud
endpoint proxy doesn't.
