### ISSUE TITLE
Remove X-Endpoint-API-UserInfo header from clients

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#338]
ESP should remove any X-Endpoint-API-UserInfo headers from clients.

This header should be generated by ESP.  ESP should not forward it.

**Comment by mangchiandjjoe** [comment]
Incoming header can be removed by nginx with proxy_set_header configuration.
Does this header should be removed by nginx or ApiManager?

**Comment by qiwzhang** [comment]
Either way.  But if doing in nginx config, we have to do it twice: one for Flex, and another for non-Flex.
So api-manager is easier.

**Comment by mangchiandjjoe** [comment]
I will remove the header inside the ApiManager.
Thanks.

**Comment by fieryorc** [comment]
Thanks! This will address our scenario where we are planning add two ESP proxy's to the same GRPC backend. One proxy will do google_id_auth and the other is pass through where we authenticate in GRPC. With this fix, we can enable this scenario.

**Comment by mangchiandjjoe** [comment]
PR https://github.com/cloudendpoints/esp/pull/339 has been merged

**Comment by fieryorc** [comment]
Any idea which release will contain this fix?

**Comment by qiwzhang** [comment]
Next release. ETA is this week, or next.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/releases/tag/v1.13.0
