### ISSUE TITLE
ESP swallows RpcException trailers metadata

### ISSUE THREAD

**Issue by TheSpy** [cloudendpoints/esp#344]
**Setup**
I am using csharp Grpc 1.8.3 client-server communication and ESP sidecar together with gcloud endpoints for monitoring.

On a server side I rise RpcException with Trailers metdata attached. (https://grpc.io/grpc/csharp/api/Grpc.Core.RpcException.html)

**Server side grpc-json communication**
When I call http endpoint on a server and an exception is raised RpcException metadata is transcoded from GRPC to JSON correctly and I can see it in HTTP response.

**Client-server communication without ESP**
When I call server method from a another service through GRPC communication directly (NOT through ESP), on a client side I get RpcException raised with Trailers metadata attached. Which works fine.

**Client-server communication with ESP**
However, when I call a server method through ESP Trailers metadata is empty.

**Problem**
I suspect that ESP does not proxy correctly trailers data. Does anyone have any input on that?

**Comment by qiwzhang** [comment]
@lizan @fengli79 Does ESP pass gRPC trailer data in pass thought case?

**Comment by lizan** [comment]
@TheSpy Do you have some sample code to reproduce this problem? Also what is the version of ESP are you using?
