### ISSUE TITLE
Is mTLS, or at least upstream TLS, supported for gRPC?

### ISSUE THREAD

**Issue by sgammon** [cloudendpoints/esp#346]
Hey there esp authors,

I am looking for clarification. I know it says in the docs that mTLS is supported via flags, but, upon closer inspection of the config template, it seems they are only applied for non-gRPC backends.

Are client certs - I.e. mTLS - supported when using “grpc://“?

Also, is upstream TLS (I.e. a gRPC server serving itself via TLS, even if client certs are not in use) supported?

**Comment by sgammon** [comment]
@lizan any help? :) or it could be that grpc operates on a higher level and nginx's support for mTLS applies when proxying to `grpc://`? @PiotrSikora

**Comment by sgammon** [comment]
@lizan / @qiwzhang, any word on this? :)

**Comment by qiwzhang** [comment]
It is not supported.   The code is there
<https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc#L104>.
 We welcome contribution to support it.

-Wayne

**Comment by sgammon** [comment]
@qiwzhang is there any update on TLS functionality, even a plan in place?

**Comment by qiwzhang** [comment]
Our resource is allocated on the needed base.  If there is such feature requirement, we will try to get it in.
Specific for this feature, PR  #465 is very close.  Just need some TLC.   I will try to locate someone to help.

**Comment by qiwzhang** [comment]
@sgammon I will work on it next week.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/582
