### ISSUE TITLE
ESP to add a header to indicate ESP version

### ISSUE THREAD

**Issue by inklesspen** [cloudendpoints/esp#347]
I understand ESP adds a header when sending the request to the backend if the request included a JWT and that JWT was successfully authenticated.

Does ESP add any headers when API keys are successfully validated? What about sending a ESP version header? Is there any way to tell by examining the HTTP request that it was processed through ESP?

Thanks!

**Comment by qiwzhang** [comment]
Yes,  you can compare the HTTP headers before ESP and after.
I think ESP only add one header; JWT token payload as "user-info" (I forget the exact header name).   It doens't add anything for api-key or ESP version.

**Comment by inklesspen** [comment]
Is this header added for all requests, or only for the requests where user info exists?

It would be good to add a header relaying the ESP version, imho.

**Comment by qiwzhang** [comment]
x-endpoint-api-userinfo  header is only added if jwt is required and the token is successfully passed verification.  This header is added in the request path to the backend.

You are suggesting adding esp-version to the response header for debugging. is that right?

**Comment by inklesspen** [comment]
Also just for general user info.

**Comment by qiwzhang** [comment]
Stackdriver structPayload log already has this info
