### ISSUE TITLE
tests in src/nginx/t all failed with latest perl 5 version 24

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#357]
bazel test //src/nginx/t:all   

failed for all tests.  The errors are:

Can't locate src/nginx/t/ApiManager.pm in @INC (you may need to install the src::nginx::t::ApiManager module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/
perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/s
ite_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/google/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/d0919d74e85a7fedd8b21f930b308d93/execroot/__main__/bazel-o
ut/k8-fastbuild/bin/src/nginx/t/unspecified_service_control.runfiles/__main__/src/nginx/t/unspecified_service_control.t line 32. 
BEGIN failed--compilation aborted at /usr/local/google/home/qiwzhang/.cache/bazel/_bazel_qiwzhang/d0919d74e85a7fedd8b21f930b308d93/execroot/__main__/bazel-out/k8-fastbu
ild/bin/src/nginx/t/unspecified_service_control.runfiles/__main__/src/nginx/t/unspecified_service_control.t line 32

But tests under third_party work.   

bazel test //third_party/nginx-tests/....

Most likely  a bug in bazel rules in https://github.com/bazelbuild/rules_perl.git

**Comment by rphillipsz** [comment]
I'm running into this while trying to run tests on Ubuntu 18.08; was there a solution?
