### ISSUE TITLE
Reload ssl certificates

### ISSUE THREAD

**Issue by hobochild** [cloudendpoints/esp#360]
Hi :wave: ,

I'm working on a k8s cluster where the ssl certificates are managed by [cert-manager]() via letsencrypt. cert-manager update the kube secret every 90 days with the new certificate. The esp is our gateway server and mounts the secret(ssl certs) for nginx. 

The problem is that nginx doesn't reload the ssl certs and continues to serve the old ones from memory, do you think it's in this projects scope to watch the ssl directory and reload when there are any changes?

**Comment by qiwzhang** [comment]
@PiotrSikora @lizan do you know if Nginx can watch ssl cert files and reload them if updated?   Or what is the best way for ESP to handle cert update.

**Comment by PiotrSikora** [comment]
@qiwzhang it doesn't watch files, you need to reload config to pick up updated certificate, by sending `HUP` signal or running `nginx -s reload`. This is graceful reload and safe to do with production traffic.

**Comment by hobochild** [comment]
@qiwzhang @PiotrSikora Thanks for the feedback! 

yea I imagine there'd need to be a process in the container that watches the SSL directory. I did see some discussion within the kubernetes community of a feature where you can restart a service when a secret change but that is suboptimal in comparison to a `nginx -s reload`.

**Comment by qiwzhang** [comment]
This is not in this project scope.
