### ISSUE TITLE
Pass api key from query parameter to header for gRPC transcoding

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#363]
If ESP is deployed in a chaining fashion,  first one is doing gRPC transcoding, and second one is for other ESP features,  both ESP proxys need api-key. 

If apikey is in the query parameter in HTTP,  when trancoding to gRPC, it should be set to header.

**Comment by qiwzhang** [comment]
Requested from  https://groups.google.com/d/msg/google-cloud-endpoints/MWsviG-mhiU/g2V-V27WBgAJ

**Comment by qiwzhang** [comment]
@lizan what do you think?

**Comment by sgammon** [comment]
@qiwzhang i second this, we just ran into this one.

**Comment by sgammon** [comment]
@qiwzhang @TAOXUY THANK YOU this helps a ton
