### ISSUE TITLE
additional_bindings do not work if you mix methods

### ISSUE THREAD

**Issue by Rajczyk** [cloudendpoints/esp#364]
I have the attempted to use both a get method and a post method for a service, and only one outside the additional_bindings becomes available in the ESP.

```
    // This RPC streams random numbers from the server.
    rpc GenerateStream (GenerateRequest) returns (stream GenerateResponse) {
        option (google.api.http) = {
          get: "/v1/generate/stream/milliseconds/{milliseconds}"
		  additional_bindings {
			post: "/v1/generate/stream"
			body: "*"
		  }
        };
    }
```

If I try an additional_bindings with a get, this works as expected.

using version 
 `gcr.io/endpoints-release/endpoints-runtime:1.15.0`

**Comment by qiwzhang** [comment]
Additional binding is not supported yet in ESP.  

It is defined here https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L303

But ESP code: https://github.com/cloudendpoints/esp/blob/master/src/api_manager/config.cc#L135

doesn't use it.

We welcome contribution to add this feature.

**Comment by Rajczyk** [comment]
thank you for pointing me to the correct area of code. I think ill attempt to build this.

**Comment by Rajczyk** [comment]
Okay so I've built a example of an API I want the ESP to be able to support. So the goal is to get the below proto file to work. 

one more question, I've been playing with the websocket functionality. I haven't found a elegant way of doing the handshake GET request, before sending data.  Has this handler already been implemented? 

```
syntax = "proto3";

package pb;

import "google/protobuf/empty.proto";
import "google/api/annotations.proto";

// The GenerateResponse is a response message containing the random number.
message GenerateResponse {
    int64 number = 1;
}

// The GenerateData message is a request message defining how the data is produced.
message GenerateData {
    // Define the amount of messages to receive.
    int64 size = 1;

    // Define the milliseconds interval between messages.
    int64 interval = 2;
}

// The GenerateRequest message contains the diffrent types of payloads.
message GenerateRequest {
    oneof payload {
        GenerateData data = 1;
        google.protobuf.Empty close = 2;
    }
}

// The Random service definition.
service Random {
    // Generate a random number.
    rpc Generate (google.protobuf.Empty) returns (GenerateResponse) {
        option (google.api.http) = {
          get: "/v1/generate"
        };
    }

    // This RPC streams a set of random numbers from the server, then closes the stream.
    rpc GenerateSet(GenerateRequest) returns (stream GenerateResponse) {
        option (google.api.http) = {
          get: "/v1/generate/set/size/{data.size}/interval/{data.interval}"
		  additional_bindings {
		    post: "/v1/generate/set"
		    body: "data"
		  }
        };
    }

    // This RPC streams a set of random number from the server, and waits for another request.
    rpc GenerateStream(stream GenerateRequest) returns (stream GenerateResponse) {
        option (google.api.http) = {
          get: "/v1/generate/stream/size/{data.size}/interval/{data.interval}"
		  additional_bindings {
			post: "/v1/generate/stream"
			body: "data"
		  }
		  additional_bindings {
			post: "/v1/generate/stream"
			body: "close"
		  }
        };
    }
}
```

**Comment by qiwzhang** [comment]
Have you tried this flag:  https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py#L493

**Comment by Rajczyk** [comment]
Yes I enabled it and did a GET request to a resource with the upgrade headers and the underlying nginx proxy responded, instead of the envoy from istio. So I can see a websocket was created. 
```
Server:[nginx] Date:[Fri, 16 Mar 2018 16:44:14 GMT]
 Content-Type:[application/json] 
Connection:[keep-alive]

```

Its just I couldn't work out how you would establish a websocket before calling a resource on the ESP. Every time I tried to do this I got a 404, Not Found, because I think the ESP didn't have a handler for the handshake? 
Kind of like when you do a dial with grpc, then call the method. Should websockets / (and even http2 streaming) not work in a similar way?  

I have done some testing with both websocket and http2 streaming and I can see the that it mostly works as I would expect. Its just the initial connection that seems a little fiddly.

**Comment by qiwzhang** [comment]
Sorry,  I am really confused.  You mentioned both Envoy from Istio and Nginx from ESP.  I don't know which  one not working.

**Comment by Rajczyk** [comment]
I made a pull request please review
#365

**Comment by toby-1-kenobi** [comment]
ESP still doesn't support additional_bindings?
I would really like this feature.

**Comment by jackwootton** [comment]
Is there any news on when ESP will support `additional_bindings`?

**Comment by qiwzhang** [comment]
@jackwootton I could not promise anything, but will try to find some resource for this feature.

**Comment by jackwootton** [comment]
@qiwzhang It looks like this pull request got quite far (https://github.com/cloudendpoints/esp/pull/365). Perhaps I could pick this up?

**Comment by qiwzhang** [comment]
Yes, it will be great if you could help.
