### ISSUE TITLE
Option to host open-api spec on a given path

### ISSUE THREAD

**Issue by ensonic** [cloudendpoints/esp#366]
We're using a grpc backend with an additional service.yaml. In order to use tools like swagger-codegen one needs the finals opne-api.spec then ESP realizes. Right now we're using a proto compiler tool (https://github.com/grpc-ecosystem/grpc-gateway/tree/master/protoc-gen-swagger), but that currently can't take data from service.yaml, so the resulting open-api.spec is incomplete. While there is a pull request for that feature, a remaining issue would be to host the api spec and hence the request for esp to allow to configure a path under which the api spec would be available.

**Comment by qiwzhang** [comment]
@ensonic not exactly understand the request here.  Could you use a usage case to clarify it?  Thanks

**Comment by ensonic** [comment]
I am asking for an commandline option that I could use like here:
https://github.com/cloudendpoints/esp/blob/master/doc/k8s/README.md#deploying-the-sample-api-to-the-cluster
e.g.: `--open-api-json="/api/v1/spec.json"
that will host the open-api spec under this path. It might make sense to offer both json/yaml via separate args. This will let people use tools like [swagger-code-gen](https://github.com/swagger-api/swagger-codegen) to generate binding to the rest service.

Right now one needs to use an external tool and figure out the hosting, since esp is fusing the proto grpc + service.yaml into the open-api.spec that it serves, but does not expose it.

**Comment by qiwzhang** [comment]
I see. Thanks. 
It is not easy for ESP to support it.  It is much easier for backend service to support it.

**Comment by ensonic** [comment]
What do you mean by backend service? Is it now esp that fused the proto grpc config with the service.yaml?

**Comment by qiwzhang** [comment]
Not,  ESP is using service config in this format.  https://github.com/googleapis/googleapis/blob/master/google/api/service.proto#L74.

It is "ServiceManagement" component fused proto grpc config with service.yaml into this format when you run "gcloud" CLI command.   But ServiceManagement did not save the original data. 

Backend service is referring to your application.  Your application server can save the open-api JSON file and serves it.

**Comment by ensonic** [comment]
Servicemanagement seems to use this tool https://github.com/googleapis/api-compiler. The whole interaction is not very clear. Sorry for asking on the wrong side.
Serving the file ourself will need to patching of the ngix config. Will give this a try.
