### ISSUE TITLE
Receiving 503 on first hits of newly deployed endpoints 

### ISSUE THREAD

**Issue by sgryschuk-va** [cloudendpoints/esp#367]
version: `gcr.io/endpoints-release/endpoints-runtime:1.12.0`
example args used: 
-s snapshot-api-test.vendasta-internal.com
-v 2018-03-27r1
-abgrpc://127.0.0.1:11000
-p 11003
-P 11005
-S 11006
-z healthz
-n /etc/nginx/mscli/nginx.conf

Issue:
The first time our service is hit with a request everything works correctly.
If instead of a single first request, if we run multiple requests in parallel the response from endpoints is 
```
{
 "code": 14,
 "message": "Failed to fetch metadata",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "internal"
  }
 ]
}
```
Then all subsequent requests work

**Comment by qiwzhang** [comment]
You can ignore the "Received non-matching report response " warning.  It is benign.  we may consider removing it.

ESP needs to call meta-data server for some credential.  It is triggered by the first request. If there are multiple concurrent requests at the start of ESP, only first triggers  the call to meta-data server,  the rest will be replied with 503, hoping client will re-try them.

The code is here:https://github.com/cloudendpoints/esp/blob/1775d95306a21ae43d71ec20f633600074ab4119/src/api_manager/fetch_metadata.cc#L87

**Comment by bbassingthwaite-va** [comment]
@qiwzhang I don't think that this could be a proper solution.  From my POV, the endpoints container needs to expose a k8s liveness check and only return 200 when it is actually capable of serving traffic. If the esp container needs to do setup (fetch tokens, fetch metadata) before serving traffic, it should do that and not serve 503s on startup.

**Comment by qiwzhang** [comment]
We could remove the current optimization to such:
if there are N concurrent requests before the first meta-data call is completed,  send N requests to meta-data server, don't fail any request. 

@mangchiandjjoe  could you help to make such change?

**Comment by qiwzhang** [comment]
Please also remove the warning of "Received non-matching report ...",  it is misleading.

**Comment by jrans-va** [comment]
Looks like the fix for this is on master, could we please get a release published that includes it @mangchiandjjoe ?

**Comment by qiwzhang** [comment]
Yes, we will make a ESP release this week.

**Comment by jrans-va** [comment]
Thanks for the release. I tried it out today and it did stop the "Failed to fetch metadata" errors we were seeing. Unfortunately, now still seeing a very similar error:
```
{
 "code": 14,
 "message": "Fetching service account token",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "internal"
  }
 ]
}
```

Looks like it's almost the exact same problem as we had with the metadata fetch - https://github.com/cloudendpoints/esp/blob/master/src/api_manager/fetch_metadata.cc#L145.

**Comment by jrans-va** [comment]
@mangchiandjjoe @qiwzhang Are you able to help with the issue in the last comment as well? Seems like basically the same issue but with the service account token instead of the metadata.
