### ISSUE TITLE
Request: release with 'client_body_buffer_size' change from endpoints-tools

### ISSUE THREAD

**Issue by rlindooren** [cloudendpoints/esp#368]
I made a change in the endpoint-tools project: https://github.com/cloudendpoints/endpoints-tools/pull/53.

I would like to start making use of it. Is it possible to create a new release of the esp Docker image (gcr.io/endpoints-release/endpoints-runtime) that contains this change?

**Comment by qiwzhang** [comment]
Next ESP release will pick up this change.  We do ESP release in every 2, 3 weeks.

**Comment by rlindooren** [comment]
Ok, thanks for your answer.
