### ISSUE TITLE
Increase the 60 second http request timeout

### ISSUE THREAD

**Issue by zeroflaw** [cloudendpoints/esp#370]
Hi,

Is there a way to increase the http timeout beyond 60 seconds?

**Comment by qiwzhang** [comment]
Which http timeout are you referring to?   The upstream http to the backend?   or the side-way http  to talke to other services such as ServiceControl?

**Comment by zeroflaw** [comment]
Honestly, I'm not sure where in the ESP the timeout is happening. I do know if I open my grpc stream directly to the backend it wont timeout. From the tracing I am at the backend for exactly 60 seconds before it gets closed. Do both the upstream and side-way http have settings that I can change for testing?

**Comment by qiwzhang** [comment]
Which platform do you run ESP on?   I remember Flex has 60 second timeout from its GCLB.  It is not from ESP.

**Comment by zeroflaw** [comment]
I'm using Kubernetes on Google Cloud, and I do have a GCLB in front of this service. If I point my ingress directly to the GRPC backend. Its working and not timing out. If I point ingress to ESP, it works for exactly 60 seconds. 

Is the GCLB adding the 60 second timeout header? which the ESP is using?

**Comment by qiwzhang** [comment]
@lizan ESP is using gRPC client library,  what is its timeout?

**Comment by lizan** [comment]
@zeroflaw I think you're hitting `client_body_timeout` which is default to 60s.
You can use a custom nginx.conf to set this manually.
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout

**Comment by zeroflaw** [comment]
I did a test and exposed a nodeport directly to the ESP, and I still timeout after exactly 60 seconds.

@lizan  Thanks for the link I will look into this and test.

**Comment by zeroflaw** [comment]
@lizan that fixed it thanks 👍
