### ISSUE TITLE
[gRPC] User-Agent header is overwritten by ESP

### ISSUE THREAD

**Issue by MrMage** [cloudendpoints/esp#387]
I wanted to use the `user-agent` header to shut out old app versions from my service. However, my backends logs indicate a user agent string of

    grpc-c++/1.4.2 grpc-c/4.0.0 (linux; chttp2; gregarious)

which is not the one provided by my client, and accessing my backend directly works.

Would it be possible for ESP to forward the original user agent header to my backend?

**Comment by qiwzhang** [comment]
ESP is calling grpc lib as grpc client when talking to backend.  Need to dig into gRPC code to see how easy to disable it.

**Comment by qiwzhang** [comment]
@lizan, @fengli79 do you know if there are ways for gRPC not setting user-agent?

**Comment by qiwzhang** [comment]
If grpc.primary_user_agent can only be set in a channel,  then it is infeasible for ESP to set it since the channel is shared by all requests.

**Comment by qiwzhang** [comment]
If you don't mind, I will close this issue

**Comment by MrMage** [comment]
I've looked into the gRPC code base and it indeed looks like there is no way to override the user agent on a per-request basis.

What would be possible, though, would be to add an `x-forwarded-user-agent` metadata header, similar to the `x-forwarded-for` proxied IP address — is this something you would consider?

Speaking of which, is it possible that the `x-forwarded-for` header is not populated for gRPC requests, either? (I might be mistaken there.)

**Comment by qiwzhang** [comment]
Current gRPC implementation in ESP is not perfect. At that time, Nginx upstream did not support http2, we had to build a Nginx content handler calling gRPC c++ library.  It is possible that many of upstream proxy features such as x-forward-for-xxx may have not be implemented. 

Just for metadata, it should not be so difficult.  It could be just some small changes in this function
https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc#L117

Hi @lizan what do you think?

Not sure if I can find somebody to work on it.

**Comment by MrMage** [comment]
Don’t worry, I’m simply transferring this info via a different metadata header now :-) Ig uess you can clos this.

**Comment by antoniomo** [comment]
Hi,

Any chance to reopen this? Even though using a separate metadata header (set from the client) is a workaround, that doesn't fix the issue. The proposed `x-forwarded-user-agent` would be a good solution requiring only backend service changes, but this workaround requires changes on clients as well, so hardly ideal and not always doable.

**Comment by qiwzhang** [comment]
Yes, we can open the issue.  But we are short of resource, we welcome any contribution.

**Comment by antoniomo** [comment]
Understood! I guess it's good to have it open to lure contributors :) Thanks!

**Comment by qiwzhang** [comment]
I guess it is related to https://github.com/cloudendpoints/esp/issues/323

This issue only wants to add "x-forwarded-user-agent" to grpc backend.

**Comment by XplittR** [comment]
Can `x-forwarded-user-agent` please be added?

**Comment by XplittR** [comment]
@qiwzhang , any updates?

**Comment by qiwzhang** [comment]
I am working on it

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/760
