### ISSUE TITLE
Is it possible to view the streaming request/response message counts in Stackdriver monitoring?

### ISSUE THREAD

**Issue by MrMage** [cloudendpoints/esp#388]
According to the debug logs, the following metrics are recorded:

    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/response_bytes"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/request_bytes"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/streaming_durations"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/streaming_response_message_counts"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/streaming_request_message_counts"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/top_request_count_by_referer"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/top_request_count_by_end_user_country"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/top_request_count_by_end_user"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/response_sizes"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/request_sizes"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/backend_latencies"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/request_overhead_latencies"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/total_latencies"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/quota_used_count"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/error_count"
    esp	May 3, 2018, 8:19:09 PM	metrics: "serviceruntime.googleapis.com/api/consumer/request_count"

In particular, there are `serviceruntime.googleapis.com/api/consumer/streaming_response_message_counts` and `serviceruntime.googleapis.com/api/consumer/streaming_request_message_counts`. It appears that this information is exposed on the Cloud Endpoints Console page as "Streaming request message counts" and "Streaming response message counts".

However, I could not find these metrics in Stackdriver Monitoring. Is it possible to access them somehow?

**Comment by qiwzhang** [comment]
Currently only cloud trace is using Stackdriver in ESP.  Its cloud trace only sending latency related info, span or child span.   ESP send above metric to Google service control service,  I am not sure if that service sending the metics to Stack driver or not.  I will check

**Comment by MrMage** [comment]
Thank you for looking into this! Were you able to find anything?

**Comment by qiwzhang** [comment]
Hi @MrMage 

streaming_response_message_counts and streaming_request_message_counts are not send to Stackdriver.  Here is the document on what metrics are supported:

https://cloud.google.com/monitoring/api/metrics_gcp#gcp-serviceruntime

**Comment by MrMage** [comment]
Thanks for the info! But where does the Endpoints dashboard get those metrics from then?

**Comment by qiwzhang** [comment]
@MrMage Endpoint dashboard backend is a Google service which can get metrics internally from other google services.   For external services, I believe you can get these metrics from exposed Stackdriver API.

**Comment by MrMage** [comment]
Filed https://issuetracker.google.com/issues/80443161.
