### ISSUE TITLE
Option to NOT reject unknown paths

### ISSUE THREAD

**Issue by moander** [cloudendpoints/esp#406]
I'm trying to replace my current NGINX proxy with ESP but all paths are not documented in the swagger file. This causes the ESP to reject those requests.

Is it possible to configure the ESP to instead pass all requests down stream?

**Comment by qiwzhang** [comment]
Yes, there is a way.  Instead of using swagger file, you may have to use gRPC API configuration.  We just call it "gRPC API configuration", it also works for HTTP/JSON too.

Here is his reference:  https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api

Here is the doc: on how to use it.  https://cloud.google.com/endpoints/docs/grpc/grpc-service-config

You can add following rule to allow all paths/methods.

http {
  rules {
    selector: "Unspecified.Paths"
    custom {
      path: "/**"
      kind: "*"
    }
  }
}

**Comment by qiwzhang** [comment]
Hi @kryzthov Does "Unspecified path" works from OpenAPI spec?

**Comment by kryzthov** [comment]
@qiwzhang There is no support for "unspecified paths/operations" in the OpenAPI spec. The gRPC API config is still the way to go.

**Comment by moander** [comment]
Thank you @qiwzhang. You say instead of the swagger file. Will the ESP still report usage statistics to Google Endpoint for my swagger paths?

I get `unknown directive "rules"` when adding the rules section to nginx.conf.

**Comment by qiwzhang** [comment]
"rules" is not in the nginx config.   It is Google Endpoint service config. You need to use "gcloud endpoints" CLI to push the service config for endpoint proxy to use it.   
Yes, usage will be reported,  but they all under method "Unspecified.Paths".

**Comment by moander** [comment]
Ok but then what's the point? Isn't monitoring what endpoints is all about? ;)

**Comment by clementdenis** [comment]
I'm trying to to something similar: I'd like the paths not matching the basePath in my OpenAPI spec to be forwarded to my backend unchanged.
According to [the documentation on the x-google-allow extension](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#x-google-allow), there's no option to do so.
Maybe a new "any" option would do the trick?

**Comment by moander** [comment]
Thank you @qiwzhang. This was exactly what I was looking for :D
