### ISSUE TITLE
Expose all JWT claims in X-Endpoint-API-UserInfo

### ISSUE THREAD

**Issue by surajbarkale** [cloudendpoints/esp#407]
We are trying to identify anonymous Firebase users passed through by ESP. However, the provided fields in `X-Endpoint-API-UserInfo` are not sufficient. Firebase provides following additional claims which are useful in this case:
```json
  "firebase": {
    "identities": {},
    "sign_in_provider": "anonymous"
  }
```
Since we are using ESP with app engine flexible, there does not seem to be a way to configure extra claims passthrough. ESP can trivially report all claims in JWT by adding following lines at the end of [`WriteUserInfoToJson()`](https://github.com/cloudendpoints/esp/blob/74fefb91bee99282076c03ed6f122e7894a988cb/src/api_manager/auth/lib/json.cc#L48) function:
```c++
  grpc_json json_all_claims;
  FillChild(&json_all_claims, &json_consumer_id, &json_top, "claims",
            user_info.claims.c_str(), GRPC_JSON_OBJECT);
```

Can you please support forwarding custom JWT claims to users?

Another alternative is to add `x-google-forward-claims` option which can be a list of claims to forward. However, I do not know where to begin for this.

On a side note I am getting `repositories.bzl:450:9: no such package '@grpc_git//': Error cloning repository: null caused by null caused by null and referenced by '//external:grpc++'.` error with a different external repository every time I try to build ESP.

**Comment by lei-tang** [comment]
The [PR 409](https://github.com/cloudendpoints/esp/pull/409) that adds JWT claims to the X-Endpoint-API-UserInfo header has been committed in https://github.com/cloudendpoints/esp/commit/d38f25b2e0a75598d505c9b2fca1e941ada3bde4.
