### ISSUE TITLE
"Invalid HTTP template" for patch method

### ISSUE THREAD

**Issue by ensonic** [cloudendpoints/esp#412]
Tested on "gcr.io/endpoints-release/endpoints-runtime:1.21"

I have this in my proto:
```proto
service ... {
 rpc UpdateBar(UpdateBarRequest) returns (Bar) {
    option (google.api.http) = {
      patch: "/apis/foo/v1/bars/{bar.id}"
      body: "*"
    };
  }
}

message Bar {
  uint64 id = 1;
}

message UpdateBarRequest {
  Bar bar = 1;
  google.protobuf.FieldMask update_mask = 2;
}
```

When starting my service I get this log warning:
```
Invalid HTTP template: /apis/foo/v1/bars/{bar.id}
```
and the update() method in my grpc service is never called when doing PATH requests on the ESP. The patch requests have all the right details as can be see in the chrome dev console and the esp logs).

The error message could also be improved to give details on whats wrong with the template since the same wording is used in multiple places.

**Comment by qiwzhang** [comment]
I think it is  possible that you may have duplicated URL template in your proto file.

I have following unit-test to try your case.  It passed
```
iff --git a/src/api_manager/path_matcher_test.cc b/src/api_manager/path_matcher_test.cc
index fb3234d..356f7e7 100644
--- a/src/api_manager/path_matcher_test.cc
+++ b/src/api_manager/path_matcher_test.cc
@@ -217,6 +217,21 @@ TEST_F(PathMatcherTest, WildCardMethodMatches) {
   }
 }
 
+TEST_F(PathMatcherTest, VariableBindingsXXX) {
+  MethodInfo* a_cde = AddPathWithBodyFieldPath("PATCH", "/apis/foo/v1/bars/{bar.id}", "*");
+  EXPECT_NE(nullptr, a_cde);
+  MethodInfo* x = AddPathWithBodyFieldPath("PATCH", "/apis/foo/v1/bars/*", "*");
+  EXPECT_EQ(nullptr, x);
+  Build();
+
+  Bindings bindings;
+  EXPECT_EQ(Lookup("PATCH", "/apis/foo/v1/bars/book", &bindings), a_cde);
+  EXPECT_EQ(Bindings({
+        Binding{FieldPath{"bar", "id"}, "book"},
+            }),
+            bindings);
+}

```

**Comment by ensonic** [comment]
Wow, there is indeed a duplicated template. Someone added a
```
patch: "/apis/foo/v1/bars/{id}"
```
(without the 'bar') also using the 'patch' verb instead of 'get'. Any change we can get a better error message in the logs?

**Comment by clehene** [comment]
Shouldn't the error be `**Duplicate** HTTP template:` at least and ideally provide the source of duplication. Is there enough context for this?

**Comment by qiwzhang** [comment]
I will open this issue to improve error message

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/657
