### ISSUE TITLE
Can't get status details to work in ESP

### ISSUE THREAD

**Issue by ffredsh** [cloudendpoints/esp#413]
I don't have too much debug information for this issue, so sorry in advance..

I currently have a GRPC server in Go that responds with the detail field populated. According to this pull, it should have been available since ESP 1.13:

https://github.com/cloudendpoints/esp/pull/334

I *have* been able to get this working with grpc-gateway, and have verified that my server is indeed setting the "grpc-status-details-bin" header in the response. However, I don't get the details in the error response I get from ESP. Here is a sample of what I get:

{
 "code": 9,
 "message": "Email is already in use",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "internal"
  }
 ]
}

Note that I get the DebugInfo detail for every error response.

**Comment by qiwzhang** [comment]
This is a known issue.   "details" field type is "Any".  You can use any message type.  When ESP tries to convert it to JSON, it doesn't have the proto descriptor linked in the ESP binary, so it could not convert it to JSON.

**Comment by ffredsh** [comment]
Is there some list of protos that *are* useable? I see from https://github.com/cloudendpoints/esp/issues/204 rpc.BadRequest seems to work. Can I reasonably expect that to always be the case?

**Comment by ffredsh** [comment]
Maybe a dumb question, but how does ESP serialize/deserialize JSON requests then? I thought ESP handles the transcoding with a provided proto descriptor file:

https://cloud.google.com/endpoints/docs/grpc/transcoding

I did ensure that we are bundling the error detail in the proto descriptor bundle we're uploading to endpoints. Is there some pruning that removes descriptors not used by services?

**Comment by qiwzhang** [comment]
gRPC transcoding is using the proto descriptor uploaded as service_config.  But error translation code is not using the the service config.

**Comment by ffredsh** [comment]
Why? Is there any technical reason why this is not possible, or just that nobody has gotten around to it yet?

**Comment by ffredsh** [comment]
Perfect, thanks! I will take a stab at it in the next few weeks. I am a bit too busy to work on it ATM. I might bug you again if I need more info :)

**Comment by ffredsh** [comment]
@qiwzhang Hey! so I took a look at it and managed to get something working! As promised, I have some questions for you...

1. I noticed that the trailer metadata actually isn't getting propagated by the upstream context in the proxy. According to the docs here: 
https://grpc.io/grpc/cpp/classgrpc_1_1_client_context.html
It looks like the trailing metadata isn't actually available unless the stream has finished? Is it because the request failed? Either way it seems kind of bizzare.. I was able to get it working by merging initial metadata + trailer metadata.

2. The type resolving is kind of tricky. On one hand I want to use the service descriptors, but on the other I need to use the linked protos for stuff like the Status. I worked around this by implementing a proxying TypeResolver that tries to resolve the type from the service descriptors first, then tries to get it from the linked descriptors. Any ideas for a better solution?

3. I noticed that the service message types are pruned in the service.json file. Any idea if endpoints is doing this? Or are we messing up the bundling somehow?

Thanks!!

**Comment by qiwzhang** [comment]
@lizan could you help to answer that.  Most of are ESP gRPC related questions.

**Comment by qiwzhang** [comment]
@ffredsh ,  I will try to upgrade gRPC.

**Comment by qiwzhang** [comment]
grpc is updated to 1.15.0 by https://github.com/cloudendpoints/esp/pull/450

**Comment by ffredsh** [comment]
Great! Will test it out and report back, thanks!!

**Comment by qiwzhang** [comment]
Not so fast,  the change is not released yet.

**Comment by ffredsh** [comment]
I compiled from source and was able to get details to work! I will close as soon as 1.25 is released. Thanks again!

**Comment by ffredsh** [comment]
Confirmed 1.26 fixes the missing details. Thanks!
