### ISSUE TITLE
Will there be api manager client libraries?

### ISSUE THREAD

**Issue by ashi009** [cloudendpoints/esp#414]
Is there a plan to add new API manager client libs for other languages?

After trying esp, I found that it might not be the best solution for a gRPC server developed on-premises. The features like logging, tracing, authentication, metrics exporting are already supported through interceptors. 

The missing bits are:

- transcoding (gRPC-web, RESTful)
- quota management
- api manager for managed config rollout

the first two are doable, so the actual missing one is the API manager client. It would be nice to have a client library ready to use for adding API manager support to my binary, and simplify my rollouts and ease some ops burden.

**Comment by qiwzhang** [comment]
Are you talking about the auto generated client library for your application service that your put ESP in front of?  If so, we don't have plan for this feature for now.

**Comment by ashi009** [comment]
Yep, that's exactly what I want. Looking forward to having that feature in the future.
