### ISSUE TITLE
nginx blocks gRPC calls with custom endpoint scheme

### ISSUE THREAD

**Issue by ashi009** [cloudendpoints/esp#415]
I have created a custom endpoint scheme and a resolver for handling service name resolving within a k8s cluster:

```
k8s://service/${namespace}/${service}
```

Which issues a gRPC request with the host header set as `${namespace}/${service}`. However, nginx doesn't like it and replied with 400:

> 2018/07/17 09:27:49 [info] 177#177: *4030 client sent invalid host header while reading client request headers, client: 10.8.0.37, server: , host: "${namespace}/${service}"

Per https://github.com/grpc/grpc/blob/master/doc/naming.md:

> Finally, the _endpoint_name_ indicates a concrete name to be looked up in a given name-system identified by the scheme and the authority. The syntax of the endpoint name is dictated by the scheme in use.

endpoint_name part is not necessarily a valid dns name, and therefore nginx should not block this.

**Comment by qiwzhang** [comment]
This is a Nginx issue.  The request is rejected by Nginx Http core module, before reaching ESP handler. Could you file the issue to Nginx?

**Comment by qiwzhang** [comment]
@ashi009 should I close this issue?

**Comment by ashi009** [comment]
Don't know if this is indeed an FR or bug for nginx, as this is a very specialized use case from its design.

I'm lean to create a local patch for nginx to make it possible.
