### ISSUE TITLE
Feature Request: OpenAPI Extension for WebSocket

### ISSUE THREAD

**Issue by dansiviter** [cloudendpoints/esp#421]
We have a requirement to use WebSocket connections from our API, but the OpenAPI specification does not support this. However, I was thinking the ESP could have an extension to permit HTTP `Upgrade` where it could be initially authenticated using the usual mechanisms then hand off to Nginx to allow the WebSocket connection. This would be somewhat similar to the behaviour Kong does which I'm currently evaluating but it doesn't leverage OpenAPI.

Alas, I'm not a C++ developer so have no idea where to start on this. Although fringe use-case, this would be a really useful addition for apps that need the low latency connection afforded by WebSockets.

**Comment by qiwzhang** [comment]
Have you tried this ESP flag  --enable_websocket.  
<https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L515>

**Comment by dansiviter** [comment]
Thanks. How would that be used in the context of GCP Endpoints and the OpenAPI definition? Are there any examples?

**Comment by qiwzhang** [comment]
ESP supports following GCE platforms:  App Engine Flex,   Compute Engine, and GKE.
Please check out this doc <https://cloud.google.com/endpoints/docs/openapi/>

This flag will not work for Flex,  but it should work for GKE and Compute Engine with docker.

For GKE example,   here is its instruction.  <https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine>

In its deployment.yaml, 

```
- name: esp
  image: gcr.io/endpoints-release/endpoints-runtime:1
  args: [
    "--http_port=8081",
    "--backend=127.0.0.1:8080",
    "--service=SERVICE_NAME",
    "--rollout_strategy=managed",
    "--enable_websocket",     <==== the new flag to enable web_socket.
  ]
```

**Comment by dansiviter** [comment]
Thanks again.

So it effectively would just ignore the `Upgrade` request in relation to the OpenAPI definitions and just pass it through? I'm assuming it would still verify authentication (via JWT or other)?

**Comment by dansiviter** [comment]
Thanks for the info. I'll run it up and see what happens.

**Comment by mkozjak** [comment]
@dansiviter Any updates if you managed to test websockets?

**Comment by dansiviter** [comment]
Apologies, I've had other priorities so not got round to it yet. I'll update as soon as I have.

**Comment by qiwzhang** [comment]
ESP (vis Nginx) supports web-socket by using --enable_websocket flag.  But JWT or api-key authentication will be by-passed since after the upgrade, it is not HTTP request any more.  ESP only works for HTTP requests.

**Comment by dansiviter** [comment]
@qiwzhang Are you saying the `Upgrade` request will be ignored even though that is a valid HTTP request? Preventing the establishment of a websocket connection via JWT is as important as any other HTTP request.

**Comment by qiwzhang** [comment]
@dansiviter good point.   Upgrade request is a HTTP request.  I believe it will pass ESP access handler.
