### ISSUE TITLE
Question: Custom nginx config for redirecting routes.

### ISSUE THREAD

**Issue by hobochild** [cloudendpoints/esp#422]
I'm trying to get around the limitations imposed by [openapi](https://cloud.google.com/endpoints/docs/openapi/openapi-limitations) on logical operators. Whereby you cannot define `OR` operator for security rules on a path. eg.

OR is unsupported
```
security:
- petstore_auth: [...]
- api_key: []
```
to get around this I thought about using a custom nginx.conf to redirect routes based on their http headers. So requests with `x-api-key` header would be redirected to the api projected route as defined in the open api spec and a jwt protect route would be redirected in the same way. This would allow you to maintain a single outward facing endpoint eg `my-service/api`.

Before starting I was wondering if anyone had tried this? And whether there are possible if anyone can could see in issues from the ESP side?

**Comment by hobochild** [comment]
Actually I just tried to add a redirect rule to the nginx conf. It works locally from inside the container. But when curling from a public I get a 401 before the redirect. So I assume the security layer (endpoints-runtime) comes before the nginx instance?

**Comment by qiwzhang** [comment]
It may work, but I am not aware of anybody have done that.

**Comment by hobochild** [comment]
Hmm, yea doesn't seem to work. Looks like the security enforcement happens before the redirect.

**Comment by qiwzhang** [comment]
Yes, you do need to provide sufficient credential before the route.  For example, if api-key is required, you need to provide it.    Same for JWT

**Comment by hobochild** [comment]
Ah yea, so the redirect I'm trying to achieve is not possible thanks for clearing that up :+1:
