### ISSUE TITLE
Do not forward host header to gRPC backend

### ISSUE THREAD

**Issue by lizan** [cloudendpoints/esp#423]
gRPC request (HTTP2) with a `host` header will lead some gRPC server reject it.

Add one more header to skip at:
https://github.com/cloudendpoints/esp/blob/master/src/grpc/proxy_flow.cc#L141

**Comment by lei-tang** [comment]
https://github.com/cloudendpoints/esp/pull/424

**Comment by lei-tang** [comment]
The PR #424 has been merged for this issue.
