### ISSUE TITLE
Using Google Service Account authentication, getting KEY_RETRIEVAL_ERROR

### ISSUE THREAD

**Issue by bourquep** [cloudendpoints/esp#442]
I have followed the [instructions here](https://cloud.google.com/endpoints/docs/grpc/service-account-authentication) to configure my API to be accessible via a service account.

When calling an API with a JWT obtained by following those instructions, ESP returns `KEY_RETRIEVAL_ERROR`, with this in the ESP logs:

```
E0829 18:37:53.181835250      12 b64.c:229]                  Invalid character {
E0829 18:37:53.181948807      12 auth_jwt_validator.cc:783]  Unable to decode base64 of secret
10.8.0.148 - - [29/Aug/2018:18:37:53 +0000] "POST /obfuscated/... HTTP/2.0" 401 0 "-" "grpc-go/1.15.0-dev"
```

In my Endpoints yaml configuration, The `jwks_uri` is set to `https://www.googleapis.com/robot/v1/metadata/x509/XXX@XXX.iam.gserviceaccount.com`.

If I curl this URL, I get this:

```json
{
    "53d7eb[...]4666c013d0": "-----BEGIN CERTIFICATE-----XXXX-----END CERTIFICATE-----\n",
    "a4f2fc9[...]06523e0bf1": "-----BEGIN CERTIFICATE-----XXXX-----END CERTIFICATE-----\n"
}
```

So according to the error log (_invalid character `{`_), it looks like ESP isn't expecting a JSON payload from the jwks_uri. However, I don't control this URI, as it is an endpoint controlled by Google...

The JWT token I am passing via the `Authorization` header, as parsed by jwt.io, contains:

```json
{
  "alg": "HS256",
  "typ": "JWT",
  "kid": "53d7eb[...]4666c013d0"
}
{
  "email": "XXX@XXX.iam.gserviceaccount.com",
  "iat": 1535567285,
  "exp": 1535570885,
  "aud": "XXX.endpoints.studyo-beta.cloud.goog",
  "iss": "XXX@XXX.iam.gserviceaccount.com",
  "sub": "XXX@XXX.iam.gserviceaccount.com"
}
```

**Comment by bourquep** [comment]
I have not tried to run the provided sample code, but I followed the instructions in that tutorial to setup my service account and configure endpoints.yaml.

What I'm saying is that the `jwks_uri` we are instructed to use in that tutorial is `https://www.googleapis.com/robot/v1/metadata/x509/SERVICE-ACCOUNT-ID`, and that URL is returning the above json which ESP can't parse because it expects base64 data.

**Comment by lei-tang** [comment]
The line "jwks_uri: https://www.googleapis.com/robot/v1/metadata/x509/SERVICE-ACCOUNT-ID" is part of the tutorial https://cloud.google.com/endpoints/docs/grpc/service-account-authentication. For that line to work correctly, it should run together with the provided sample code. If the tutorial does not work, then the information of which part in the tutorial is not working will be helpful for diagnosing the problem.

**Comment by bourquep** [comment]
I have replaced the URL from the tutorial by my own (repalced SERVICE-ACCOUNT-ID with mine).

Again, what I am trying to convey is that this Google-owned URL returns a JSON payload, and ESP can’t handle that payload properly.

**Comment by bourquep** [comment]
@lei-tang I'm kind of stuck because of this issue...

**Comment by bourquep** [comment]
I have created another service account by following the tutorial instructions, and here is the `jwks_uri` corresponding to that account:

`https://www.googleapis.com/robot/v1/metadata/x509/test-esp-442@studyo-beta.iam.gserviceaccount.com`

This endpoint returns the following json payload:

```json
{
    "3a80c7a56d8cfb731ebdb22cbe909556b3cf9840": "-----BEGIN CERTIFICATE-----\nMIIC+jCCAeKgAwIBAgIIRbNgpysdjDIwDQYJKoZIhvcNAQEFBQAwIDEeMBwGA1UE\nAxMVMTE3NjkyNDE0NTE0MzY4ODU5NDU2MB4XDTE4MDkwNDE0NTQwNFoXDTI4MDkw\nMTE0NTQwNFowIDEeMBwGA1UEAxMVMTE3NjkyNDE0NTE0MzY4ODU5NDU2MIIBIjAN\nBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsprr1PaSc8KsQyMRot5FitRLYTIT\nwa0BnJe39qHRaCMC6t7z6gFio07TjnHS3ctV2EsTy6FF4n6MwezDszNJhrF3JAiX\nqcoqgkTZ+brpPaMK2ub4SZvwt0w4muznagwpEt7QnTR2vNQcLIXVJ5JPYcph8eho\nhAHgqr1ixtey77K9CtjDwJvRnZDV3yx+Rp8UuAH1oxXvo/P7qG9dX5+c3+GNQFwu\n9AxFJf0fuW6jExhyr/GZa89t0Nqb7/s1BJdO4YIuomSVzIfGJFAHQEyK7eU5ely7\nKP/S0Nz8kf2m9J/5/AK7gzDxJVgWEmOztT+ih/bl2MHXkrwHNKn0iFK+pQIDAQAB\nozgwNjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAWBgNVHSUBAf8EDDAK\nBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOCAQEAJOVH6aZChuso5rswD9PSmb2o\nBrH2QBBJ/CbEMKn81zfD8wGMN/xRDL3c9owwePnTLWD9UYjEOL/mOenRSRTgFjwe\nQAVRUk6yHovG5Y39xmwqNQ/9Hz0Ej/o+TVbglIkuUmgaxzMjyX5Gj+87fSjBivWc\nZAbIqab7q4uWBPZqQv49lbo/enaHn80jrKwHufJrMNe84LdJVg9sK2DgzI1SKcJf\nXQikp3l+EQY83xt6smuRf4jKP62zqpv/KchIaanmIncTi4A7O4He6jNGAEFglEZJ\nCl6oJ0B7rsS7Ds7zKrlfUgQy4Af48m2ild+KqT2u+5saszCNd+7ujaen5IsCfw==\n-----END CERTIFICATE-----\n",
    "a162b58b7d99f506d5eed4559aa999e9d0780c4e": "-----BEGIN CERTIFICATE-----\nMIIDMDCCAhigAwIBAgIIBIOlPMGWMv0wDQYJKoZIhvcNAQEFBQAwOzE5MDcGA1UE\nAxMwdGVzdC1lc3AtNDQyLnN0dWR5by1iZXRhLmlhbS5nc2VydmljZWFjY291bnQu\nY29tMB4XDTE4MDkwNDE0NTQwMloXDTIwMDkwMzE0NTQwMlowOzE5MDcGA1UEAxMw\ndGVzdC1lc3AtNDQyLnN0dWR5by1iZXRhLmlhbS5nc2VydmljZWFjY291bnQuY29t\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApUrPW/P27k2x5KZhD6n2\nrAzy69zLjPEMj2uw48tFe6Mz9d25XmMWqhdPiHuw9eY0rjJN92EuArBEgmQGCdCc\ntKTqqB8h0dTYwaVOzd9m5oaDyy6c/w6GYIncbWERNFo6knFI8fBInHT6SbU/zo/d\nRf31whZd5SK1qDPnjmxPbjqabX5FZyMLFGc67JH+gu2P/kraSgI2R+ks48zUpyii\n5MflWHbMpMqOmgy0wapzyna11JD/OMoNXfJmE2Qv+hrhQYJF9zOgptG9uybObQZH\n0evJdlZ+sQ6UOvRNDcqzZkF2XTw19Wwor5ra1OM9POGcyqEi8hqd4+iLXECEGQih\nnQIDAQABozgwNjAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAWBgNVHSUB\nAf8EDDAKBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOCAQEANMsox1oazkDgBfxn\nN5iEEcLpZYn/W5WRE+d2gkUH1dCipyYlc3R+EDdzooN609EqfcZt5YO2yTLIaX73\nveggCl0eI9yl/yJKAIHZQWDtWv3KqxsF2WNBGPiBOM+ZW2/+4ln9X41AHYh6a1Ze\n7DPMnPBUuJkistL66TVFJpuX/A3BIs+wKDxHCgIijgxeqOApc+sHvBKF5KJq3MU4\nlFKrukr9EvjjFbVIaRI7Mrhj+BaeO0hhy4gX8G4333WemIEU0BAxpxiJPl9Dp0is\nb+hd6V4M6GlTCTdv6HVRmaGa3eGwTeBQTzu9PtQUHGUPiQstxAlUqu52SG86uuje\noPhx+g==\n-----END CERTIFICATE-----\n"
}
```
 Which ESP is unable to parse.

**Comment by qiwzhang** [comment]
It seems that response from https://www.googleapis.com/robot/v1/metadata/x509/test-esp-442@studyo-beta.iam.gserviceaccount.com doesn't following the jwks standard defined in https://tools.ietf.org/html/rfc7517.

The question is: should ESP supports such response?

**Comment by bourquep** [comment]
Considering that this is Google’s own service account endpoint, and that it is used to perform service account auth with Cloud Endpoints, and that it means the tutorial is broken, I’d say yes...

**Comment by qiwzhang** [comment]
It turns out it is a documentation bug.  You should use this jwks_uri:  https://www.googleapis.com/service_accounts/v1/jwk/{SERVICE-ACCOUNT-ID}

It will reply with correct jwks that ESP supports. 

We will update the instruction.

**Comment by qiwzhang** [comment]
https://github.com/GoogleCloudPlatform/python-docs-samples/pull/1683

**Comment by qiwzhang** [comment]
Please ignore my previous two comment.

ESP doesn't support alg "HS256".  It only supports "RS" or "EC".   The code is here:
https://github.com/cloudendpoints/esp/blob/master/src/api_manager/auth/lib/auth_jwt_validator.cc#L704

**Comment by bourquep** [comment]
But how can I specify a different algorithm when I create the service account key?

<img width="484" alt="image" src="https://user-images.githubusercontent.com/65096/45064425-a0cf2580-b081-11e8-9926-d0c104e49469.png">

**Comment by liminw** [comment]
@bourquep, The key you have shown is x509 public key format, and ESP supports it today. 

I believe the problem is that your JWT's "alg" is set to "HS256", which means symmetric key algorithm. You should set it to "RS256" instead.

**Comment by liminw** [comment]
@qiwzhang The reason @bourquep saw the error is that for symmetric key, ESP expects the key string, which should base64 encoded. But in the case of asymmetric keys, there can be multiple keys, and hence, is in JSON format. Maybe we can improve the error message so that this kind of mistake can be avoided.
