### ISSUE TITLE
[GRPC]: ESP silently fails if request has Connection header

### ISSUE THREAD

**Issue by burdiyan** [cloudendpoints/esp#443]
When you setup Nginx Ingress Controller in Kubernetes in front of ESP, by default Ingress Controller sends `Connection` header using GRPC backend protocol (which I will report as a separate bug for them) which violates HTTP2 spec.

The issue with ESP is that it silently fails without any notice. It took me almost 4 days to discover this problem. If you enable debug mode ESP says `client sent HTTP/2 request with "Connection" header while reading client request headers` with level of `info`, which probably should be error or warn at least.

**Comment by qiwzhang** [comment]
The code is in Nginx core, not in ESP handler.  You may have to file this issue to Nginx.
