### ISSUE TITLE
Allow ESP to work with read-only filesystem

### ISSUE THREAD

**Issue by gunsch** [cloudendpoints/esp#444]
Currently crashes when trying to run on GKE with read-only filesystem.

Context: https://groups.google.com/forum/#!topic/google-cloud-endpoints/Gl7ZP9xMr_Y

**Comment by kyessenov** [comment]
You can take a look at how istio does it. You would need to change the pod spec to use emptyDir volume with memory medium for tmpfs. See example: https://github.com/istio/istio/blob/00abab79d96eb74b1b021be6f81c91f25a262768/pilot/pkg/kube/inject/testdata/inject/hello-multi.yaml.injected#L124

**Comment by stjasink** [comment]
There is some config that still prevents ESP from running on a read-only file system that I can't find a way to override.

I have various emptyDir mounts to provide writable dirs:

          - mountPath: /var/run
            name: var-run-for-nginx
            readOnly: false
          - mountPath: /var/log/nginx
            name: var-log-for-nginx
            readOnly: false
          - mountPath: /var/cache/nginx
            name: var-cache-for-nginx
            readOnly: false
          - mountPath: /etc/nginx/endpoints
            name: endpoints-config-for-nginx
            readOnly: false
          - mountPath: /home/pex
            name: home-for-pex
            readOnly: false

On startup, it generates config for nginx which by default is written to `/etc/nginx/server_config.pb.txt` which is an existing dir.  I use a parameter to set this to use one of the mounted writable dirs:  `"--server_config_generation_path", "/etc/nginx/endpoints/server_config.pb.txt"`

Now it will write the file to that writable dir, but the config that references where to _read_ that file does not update, so it won't find the file and won't start up.  The config location to read is hardcoded here: https://github.com/cloudendpoints/esp/blob/master/start_esp/nginx-auto.conf.template#L139

I am working around this by creating a Docker container based on ESP that includes a patched config template that points to my writeable dir.  Obviously this is not ideal.  Any chance this could be looked at please?

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/pull/563

**Comment by stjasink** [comment]
@qiwzhang Release 1.31 fixed my issue that I posted about above.  Thanks!
