### ISSUE TITLE
Multiple authorization headers

### ISSUE THREAD

**Issue by loredond** [cloudendpoints/esp#455]
Hello, 

I'm deploying an api protected by auth0 which is behind a nginx proxy protected by a basic authorization, so i'm trying to pass two authorization headers in my request, one for the basic auth, the other one for auth0, like so : 

`authorization: Bearer YXNkZnNhZGZzYWRmOlZLdDVOMVhk, Basic YXNkZnNhZGZzYWRmOlZLdDVOMVhk`

But it seems like ESP can't parse both, i have `JWT validation failed: BAD_FORMAT` error.

Is it a bug, or am i doing something wrong ? Is there a way to have two authorization headers in ESP ?

Thanks.

**Comment by qiwzhang** [comment]
Sorry,  ESP doesn't support requests with more than one JWT tokens.
