### ISSUE TITLE
Retries and Timeouts for calls to Service Control API

### ISSUE THREAD

**Issue by chad-orwig** [cloudendpoints/esp#456]
We are using Endpoints with ESP and had an event yesterday where many of our requests were timing out and generating the following logs

```
E  2018/10/10 21:47:31 [warn] 13#13: upstream server temporarily disabled
 
E  2018/10/10 21:47:31 [error] 13#13: upstream timed out (110: Connection timed out)
 
E  2018/10/10 21:47:31[error]13#13: Failed to call https://servicecontrol.googleapis.com/v1/services/{**projectInfo**}:check, Error: ERROR: Failed to connect to server., Response body: 
 
E  [libprotobuf ERROR external/servicecontrol_client_git/src/service_control_client_impl.cc:213] Failed in Check call: Failed to connect to service control
```

We opened a support ticket with Google and the only suggestion was to implement retries.  Obviously, retries are only helpful if the initial try aborts in a reasonable time.  Therefore we are requesting that a configuration option for retries and timeouts to the Service API be added to ESP.

**Comment by qiwzhang** [comment]
The request connection timeout for Check call is 5 second.  it is hard coded,  users could not change it.  

But I don't think it will help much by allowing users to config it.

**Comment by chad-orwig** [comment]
I feel like retries and timeouts go hand in hand.  If the best solution is to retry then we need some control over timeouts as well.  We could feasibly implement retries a layer above ESP but we would want much lower timeout values than 5s in that case.

Ideally, ESP handles both and we can just configure.  If not, we end up having to roll our own service API integration or give up on endpoints entirely.

**Comment by qiwzhang** [comment]
Google service control is supposed to have high availability, over 99.999%.   Beside, there is local cache for the Check result.  So if your network to Google service is good,  you should not run into this timeout issue very often.   If your service constantly run into this issue,  you should check your network, if it is good, file an issue with Google Service control service team.

**Comment by chad-orwig** [comment]
We're running inside GKE so our network is your network.  We've seen this issue before.

**Comment by qiwzhang** [comment]
In this case, file an issue with Google Service Control team. they should debug the timeout issue.

**Comment by chad-orwig** [comment]
Ok, I will re-open our service ticket with this info about 5 9s reliability.  Thank you for your responsiveness.
