### ISSUE TITLE
esp nginx config does not match the A+ security rating

### ISSUE THREAD

**Issue by JubbaSmail** [cloudendpoints/esp#459]
I have to run esp with custom niginx to follow the A+ security rating (see: https://cipherli.st), would be nice if this would be included by default

**Comment by qiwzhang** [comment]
we can add a start_esp flag as --enable_a+_security_rating to add these config into Nginx config.

@lei-tang could you help?

**Comment by lei-tang** [comment]
The PR https://github.com/cloudendpoints/esp/pull/467 has been created to address this issue.

**Comment by qiwzhang** [comment]
This PR #467 is half-baked.  ESP will not work by simply enabling the flag.  It requires users to generate dbparam.pem and define DNS_IP variables.
