### ISSUE TITLE
Add proxy_buffer_size, proxy_buffers support for CLI

### ISSUE THREAD

**Issue by aaabramov** [cloudendpoints/esp#460]
I will be more than happy to contribute.
The only question I have is which default values to set?

**Comment by qiwzhang** [comment]
could you describe which buffer size are you referring to? 

We have these two flags:

--client_body_buffer_size

https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L555

and 

--client_max_body_size

https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L547

**Comment by aaabramov** [comment]
Hi, I mean exactly:
- [`proxy_buffer_size`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size)
- [`proxy_buffers`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffers)

**Comment by qiwzhang** [comment]
We can add two start_esp flags for them.     How about this: if the flag is not set,  not add it to nginx config.   By this way, you don't need a default.

**Comment by qiwzhang** [comment]
@aaabramov  could you create a PR for that?

**Comment by aaabramov** [comment]
@qiwzhang yep, sure.
Could you give me an example how to achieve this:

> if the flag is not set, not add it to nginx config

**Comment by qiwzhang** [comment]
How about this:
https://github.com/cloudendpoints/esp/blob/master/start_esp/nginx-auto.conf.template#L116
