### ISSUE TITLE
Multiple authentication schemes (jwt + key)

### ISSUE THREAD

**Issue by bdahon** [cloudendpoints/esp#469]
Hi,

We have some endpoints that are secured using JWT tokens (auth0). These endpoints so far were only used by our front ends (using auth0 tokens), but now we need to setup access using api keys as well for machine to machine communication. What we need is the ESP to authenticate the request whenever one or the other authentication method is validated (api key OR jwt).  Is this something that is an option for the esp roadmap ?

Thanks

**Comment by qiwzhang** [comment]
Sorry,  we don't have (Api-key OR JWT) security requirement in our roadmap.

**Comment by bdahon** [comment]
@qiwzhang Thanks for you response. Just out of curiosity, how would you handle this requirement in a CGP/K8S deployment ?
