### ISSUE TITLE
Option to add Strict-Transport-Security header to response

### ISSUE THREAD

**Issue by guimarca** [cloudendpoints/esp#473]
The `Strict-Transport-Security` response header is a very common request from customers after an ethical hacking audit. Would be nice to have the option to add it to ESP responses via argument(s) to the start script.

**Comment by lei-tang** [comment]
Yes, I will create a PR for it.

**Comment by guimarca** [comment]
Wow, that was fast, thank you. Any idea when you'll make the next release?

**Comment by qiwzhang** [comment]
Probably next week.

**Comment by guimarca** [comment]
We have been testing the image 1.26.0, which includes this feature, and were not seeing the header in the responses. It turned out that adding the `always` parameter fixed the issue. Would you mind to add it it?

` add_header 'Strict-Transport-Security' "max-age=31536000; includeSubdomains;" always;`

**Comment by qiwzhang** [comment]
@guimarca could you try moving the "add_header" inside the location,  at the same level as the other add_headers.

I just read its [doc](http://nginx.org/en/docs/http/ngx_http_headers_module.html).  we added to the wrong place ( at server level).   If location level has add_header, it will not inherit from server level.

@lei-tang could you help to fix it?

**Comment by lei-tang** [comment]
@guimarca I created the PR https://github.com/cloudendpoints/esp/pull/487 to move the strict_tls_security header from server level to location level. Can you review this PR and verify whether it solves the problem?

**Comment by qiwzhang** [comment]
Does that mean we have to add "add_header" in all three places?  

if cors == option 
    here
if cors
    here
here

It looks ugly. Is there better way?

**Comment by bfin** [comment]
@qiwzhang There's a much better way!

The nginx headers-more module is a popular extension to the core headers module that adds some new directives, including `more_set_headers` which will add or replace a given header without the nesting issues.

Ref:
https://github.com/openresty/headers-more-nginx-module
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/headers-more/

In this example, the response to an OPTIONS request would include both the `X-Header-1` and `X-Header-2` headers while the response to a non-OPTIONS request would only include the `X-Header-1` header – the nesting doesn't matter:
```
    more_set_headers 'X-Header-1: A';

    if ($request_method = 'OPTIONS') {
      more_set_headers 'X-Header-2: B';
    }
```

The nginx ingress controller for kubernetes uses this module for CORS headers (https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl#L783-L797), although its usage is a bit redundant.

**Comment by qiwzhang** [comment]
Thanks @bfin for the point.  We will look into it to see if we can use it to simply our config.

**Comment by qiwzhang** [comment]
raised as separate issue to track it
