### ISSUE TITLE
need to add parameter for using proxy for validation of google credentials

### ISSUE THREAD

**Issue by xavier-re** [cloudendpoints/esp#486]
Hello,
to be PCI compliant on my infra, I need the ESP to go through a proxy to validate the google credentials. (i need to whitelist any outbound connection, and servicecontrol.googleapis.com doesnt seems to be a list of static ips)

Each time there is a connexion, the ESP validates with google the auth/token provided.

I tried starting start_esp with the correct environment variables http_proxy and https_proxy
it works for the first request to accounts.google.com.

However on subsequent calls, to servicecontrol.googleapis.com, it does not use the http_proxy provided, it connects directly.

Is there a way for the esp to use a proxy while connecting to servicecontrol.googleapis.com ?
thanks.

**Comment by qiwzhang** [comment]
ESP is using very hacked code [http.cc ](https://github.com/cloudendpoints/esp/blob/master/src/nginx/http.cc) to make side-way http calls, e.g. call to servicecontrol, jwt public key server or gcp metadata server.   

This code is not easy to add any new features, such as using http_proxy.
