### ISSUE TITLE
Istio tracing integration with ESP

### ISSUE THREAD

**Issue by lei-tang** [cloudendpoints/esp#488]
It is reported that when using Istio and ESP together, there are two trace spans generated, one for Istio and the other for ESP.  This issue is created to combine two trace spans into one.

Cause of the issue
ESP adds the tracing information to the X-Cloud-Trace-Context header. Istio does not use the X-Cloud-Trace-Context header but uses the following headers for tracing:
x-request-id
x-b3-traceid
x-b3-spanid
x-b3-parentspanid
x-b3-sampled
x-b3-flags
x-ot-span-context
As Istio and ESP have their own tracing headers, two separate trace spans are generated.

**Comment by qiwzhang** [comment]
After a meeting with the users.  It turns out this is NOT what they asked.

**Comment by peter-fe** [comment]
@qiwzhang, @lei-tang 

We have exactly the same issue with Istio + ESP (even though this may not was requested by the originator of this issue). 

> After a meeting with the users. It turns out this is NOT what they asked.

We had a talk with Dan Ciruli regarding this topic early this year and we also asked for support on [Google groups](https://groups.google.com/forum/#!searchin/google-cloud-endpoints/istio%7Csort:date/google-cloud-endpoints/tTEzRpnl1Yc/KNfcjTkTBgAJ), late last year. 
The response in the Google groups was very promising, I think maybe this issue (#488) was in mind when posting the response.

Currently our tracing breaks, or to be more accurate, splits occasionally in two spans or most of the time shows just a part of the complete call path, when running ESP within an Istio mesh, due the complete segregation of x-cloud-trace-context and open tracing x-b3 worlds.

**In out case we see the following variants how traces appear in SD:**

- Istio is opening a new trace, we get everything from start to end (as our apps can handle both formats), except the valuable tracing from ESP.

- ESP is starting a trace, so we get everything downstream but not the Istio gateway & side car portions of the call.
 
- Istio is opening a trace and ESP is opening a trace and we have some split brain tracing where a human being has to correlate, by additional ids (request-id, additional b3-headers) to get one consolidated view of the call.

Everything is doable, but causes additional overhead, friction and needs deeper knowledge of identifiers within the logs or traces to make a correlation possible.

As Istio gets more and more integrated into other Google products (or third party ones used in the GCP) it would make sense to agree on some common view/format regarding tracing headers, or at least support other formats too, to get a smoother and tighter integration.

We would be very interested in supporting the x-b3 headers in ESP, even if ESP is just using the x-b3 ones to extend the trace by its own spans and keeps emitting only the x-cloud-trace-context ones downstream (emitting both would make more sense, but if not, we can convert that in our apps, that's still better than partial or duplicate/partial traces)

best,
Peter

**Comment by qiwzhang** [comment]
So you are asking ESP to extract zipkin trace context headers (x-b3) for its trance parent id. 

I will re-open this issue.

**Comment by peter-fe** [comment]
@qiwzhang
Exactly, that would be a great deal, I assume not only for us!
Thx for re-opening!

**Comment by peter-fe** [comment]
@qiwzhang, is there anything we can do to assist on that topic or when we can expect progress on that?

Best,
Peter

**Comment by qiwzhang** [comment]
Unfortunately, this is categorized as new features.  The resource is very limited for the new feature requests. I don't have any ETA for this feature.
