### ISSUE TITLE
Billing cost for calls ServiceController.Report

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#501]
I checked the service under load of 100 requests per second and saw how the cost of using Google Service Control in Cloud billing, I also found a dependency on the API of the google.api.servicecontrol.v1.ServiceController.Report.

I do not quite understand why ESP sends requests for this service and how to reduce the consumption of money. I plan to do more and more services with ESP and I would not want to pay $ 40 per day extra with a load of 100 rps.

Current options from kubernates conf: 

```
        args: [
          "--http_port=9000",
          "--http2_port=9001",
          "--backend=grpc://127.0.0.1:50051",
          "--service=XXXXX",
          "--service_account_key=XXXXXX",
          "--rollout_strategy=managed",
          "--disable_cloud_trace_auto_sampling",
          "-z=healthz",
        ]
```

Help please, I do not understand at how I can improve on the situation.

**Cloud Billing**
![2018-12-07 0 14 49](https://user-images.githubusercontent.com/1708175/49612824-e79d2600-f9b6-11e8-8cab-04d51621d041.png)

**servicecontrol.googleapis.com/metrics**
![2018-12-07 0 12 54](https://user-images.githubusercontent.com/1708175/49612828-e966e980-f9b6-11e8-9d55-f0a1109b05ed.png)

**Comment by qiwzhang** [comment]
ESP is making two calls to Google ServiceControl service;  Check and Report.  In theory, one for each request.   But Check() call has local cache,  If it is a cache hit,  not remote call is made.   Report calls are batched up to 1000, or 1 second.

Check() can be disabled by setting "allow_unregistered_call" to true.   But there is not way to disable Report call.

**Comment by qiwzhang** [comment]
Here is the ESP pricing: https://cloud.google.com/endpoints/pricing-and-quotas

**Comment by arturgspb** [comment]
Thanks, I missed the call charge documentation. =(

ESP is running locally for me, it’s a pity that I have to pay for calls to api outside the GCP.

I do not mind paying for call logs, but not for the self API calls themselves - this is strange, since I do not occupy the resources and channel of the Internet of the GCP. This is very sad.

**Comment by arturgspb** [comment]
@qiwzhang 

By the way, for what purpose is a Report api call?

**Comment by qiwzhang** [comment]
ESP sends metrics and logs to Google service control service in the Report calls about the requests.
Here is an example of data it is sending.  https://github.com/cloudendpoints/esp/blob/master/src/api_manager/service_control/testdata/report_request.golden

**Comment by arturgspb** [comment]
@qiwzhang 

Tell me how can I adjust the frequency of the call Report API and the size of the request (1000 cache entries)?

I see proto conf https://github.com/cloudendpoints/esp/blob/74fefb91bee99282076c03ed6f122e7894a988cb/src/api_manager/proto/server_config.proto#L124

and 
https://github.com/cloudendpoints/esp/blob/74fefb91bee99282076c03ed6f122e7894a988cb/src/api_manager/proto/sample_server_config.pb.txt#L12

But I don’t understand if I can somehow convey these parameters when starting ESP?

**Comment by qiwzhang** [comment]
server_config is generated at start_esp.py script from this template https://github.com/cloudendpoints/esp/blob/master/start_esp/server-auto.conf.template

Not, there is no much room to increase the batch side.  There is a 4MB side limit in the server side for each Report call.  I think the default batch side is pretty close to that limit.

**Comment by arturgspb** [comment]
Thank you. Let's summarize to confirm that I understood you correctly.
Now there is no way to greatly reduce my expenses when using esp. It is possible to remove the allow_unregistered_call setting, but this will not greatly affect the cost as far as I understand.

Is that right?

**Comment by qiwzhang** [comment]
One thing I am not clear; which expense are you referring to?    Is it the number of ServiceContro.Report calls and Google charges you by the number of calls?   or The expense from Google Endpoints pricing where it charges you by the number of requests ESP have been proxy-ed?

Google Endpoint team is not aware the former,  but we can adjust the pricing for the latter.
