### ISSUE TITLE
ESP 1.27 causing CloudFlare Proxy SSL Handshake Error

### ISSUE THREAD

**Issue by JubbaSmail** [cloudendpoints/esp#502]
Here are the description of the situation:

- We are proxing https traffic from CloudFlare to our k8s app
- CloudFlare will use our wildcard cert *.xyz.com to terminate the SSL
- The k8s consist of two containers (ESP and .Net Core app)
- ESP (v 1.27) run with custom config and uses a certificate generated by letsencrypt.org (the cert is vaild and I was able to establish secure connction from a browser if I access the APP directly without CloudFlare)
- By visiting the website a.xyz.com, CloudFlare report the following "**525 Origin SSL Handshake Error**"
- Using ESP (v 1.22) with the exact same setup and all works as expected.

CloudFlare descripe **525 Origin SSL Handshake Error** in this link:
https://support.cloudflare.com/hc/en-us/articles/200278659-Error-525-SSL-handshake-failed

**Comment by qiwzhang** [comment]
Could you double check if "server_name" field is set correctly in your custom Nginx config. It is this line https://github.com/cloudendpoints/esp/blob/master/start_esp/nginx-auto.conf.template#L83

ESP 1.27 upgraded Nginx from 1.13 to 1.15.   You can search Nginx to see if it introduced any improvement or bugs related to SNI

**Comment by JubbaSmail** [comment]
right, I don't have  "server_name" in my config

**Comment by qiwzhang** [comment]
"sever_name" is required for SNI to work.

**Comment by JubbaSmail** [comment]
but then everyone how didn't define it in the custom config and are using ESP:1 will face this issue on next deployment, is there a way to avoid that?
