### ISSUE TITLE
ESP does't close the stream with client disconnect for a streaming GRPC call

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#504]
We're using ESP for GRPC calls, both streaming and non-streaming, and for connections from our mobile clients we're seeing an issue on ESP where it does not seem to handle client/stream disconnects correctly on streaming calls.

We have the following setup:

mobile client -> (TCP LB in GCP) -> Envoy (for GRPC load balancing and routing) -> ESP -> our JVM

I can repro by killing our mobile app, we see the client end in the client log, envoy logs the end of the request, but ESP doesn't emit a log entry for it and our JVM continues as if the client is still around.  After 60 minutes duration on the request, our JVM responds with a DEADLINE_EXCEEDED, and then ESP emits a log for the request.

1) Is it possible to get more debug at the GRPC/http2 from ESP?  I tried setting nginx to debug but didn't see anything useful at this level.  I also tried some of the GRPC environment variables (GRPC_VERBOSITY and GRPC_TRACE) but those didn't seem to do anything.

2) Is it possible to get a ESP build with the latest nginx version?  One of our SWE's saw some HTTP2 changes in the release notes (https://nginx.org/en/CHANGES-1.14) that could be related to what we're seeing.  We tried the latest ESP build but it didn't resolve the issue.

**Comment by qiwzhang** [comment]
Sorry, some other issues came up in production, I was finally able to get debug output.  I used a 1.27.0 container, I'm doing a .. grep " \*1677" which seems to line up with getting the debug logs that matter.  I stripped off most of the beginning of the request logs as it's 324 lines total.  22:17 the streaming request starts (Observe), I killed it and the stream RST flows across at 22:18:02, at 23:17:42 our server deadline kicks in and the server responds with a DEADLINE_EXCEEDED.

2018/12/18 22:17:42 [debug] 12#12: *1677 http2:1 DATA frame 00000000020021A8 was sent
2018/12/18 22:17:42 [debug] 12#12: *1677 http2 frame sent: 00000000020021A8 sid:1 bl:0 len:4356
2018/12/18 22:17:42 [debug] 12#12: *1677 http write filter 0000000000000000
2018/12/18 22:17:42 [debug] 12#12: *1677 http copy filter: 0 "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 22:17:42 [debug] 12#12: *1677 NgxEspGrpcServerCall::Write: completed synchronously
2018/12/18 22:17:43 [debug] 12#12: *1677 NgxEspGrpcServerCall::Write: Writing 8507 bytes
2018/12/18 22:17:43 [debug] 12#12: *1677 malloc: 00000000020D8520:8512
2018/12/18 22:17:43 [debug] 12#12: *1677 http output filter "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 22:17:43 [debug] 12#12: *1677 http copy filter: "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 22:17:43 [debug] 12#12: *1677 http postpone filter "/nestlabs.gateway.v2.GatewayService/Observe?" 00007FFF58035930
2018/12/18 22:17:43 [debug] 12#12: *1677 write new buf t:1 f:0 00000000020D8520, pos 00000000020D8520, size: 8512 file: 0, size: 0
2018/12/18 22:17:43 [debug] 12#12: *1677 http write filter: l:0 f:1 s:8512
2018/12/18 22:17:43 [debug] 12#12: *1677 http write filter limit 0
2018/12/18 22:17:43 [debug] 12#12: *1677 http2:1 windows: conn:268431100 stream:268431100
2018/12/18 22:17:43 [debug] 12#12: *1677 http2:1 create DATA frame 00000000020021A8: len:8192 flags:0
2018/12/18 22:17:43 [debug] 12#12: *1677 http2:1 create DATA frame 0000000001BA5708: len:320 flags:0
2018/12/18 22:17:43 [debug] 12#12: *1677 http2 frame out: 0000000001BA5708 sid:1 bl:0 len:320
2018/12/18 22:17:43 [debug] 12#12: *1677 http2 frame out: 00000000020021A8 sid:1 bl:0 len:8192
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL buf copy: 9
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL buf copy: 8192
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL buf copy: 9
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL buf copy: 320
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL to write: 8530
2018/12/18 22:17:43 [debug] 12#12: *1677 SSL_write: 8530
2018/12/18 22:17:43 [debug] 12#12: *1677 http2:1 DATA frame 00000000020021A8 was sent
2018/12/18 22:17:43 [debug] 12#12: *1677 http2 frame sent: 00000000020021A8 sid:1 bl:0 len:8192
2018/12/18 22:17:43 [debug] 12#12: *1677 http2:1 DATA frame 0000000001BA5708 was sent
2018/12/18 22:17:43 [debug] 12#12: *1677 http2 frame sent: 0000000001BA5708 sid:1 bl:0 len:320
2018/12/18 22:17:43 [debug] 12#12: *1677 http write filter 0000000000000000
2018/12/18 22:17:43 [debug] 12#12: *1677 http copy filter: 0 "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 22:17:43 [debug] 12#12: *1677 NgxEspGrpcServerCall::Write: completed synchronously
2018/12/18 22:18:02 [debug] 12#12: *1677 http2 read handler
2018/12/18 22:18:02 [debug] 12#12: *1677 SSL_read: 13
2018/12/18 22:18:02 [debug] 12#12: *1677 SSL_read: -1
2018/12/18 22:18:02 [debug] 12#12: *1677 SSL_get_error: 2
2018/12/18 22:18:02 [debug] 12#12: *1677 http2 frame type:3 f:0 l:4 sid:1
2018/12/18 22:18:02 [debug] 12#12: *1677 http2 RST_STREAM frame, sid:1 status:0
2018/12/18 22:18:02 [info] 12#12: *1677 client closed stream 1, client: 10.21.171.10, server: , request: "POST /nestlabs.gateway.v2.GatewayService/Observe HTTP/2.0", host: "apigw.loadtest3.nestlabs.com:443"
2018/12/18 22:18:02 [debug] 12#12: *1677 http run request: "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 22:18:02 [debug] 12#12: *1677 http reading blocked
2018/12/18 22:18:02 [debug] 12#12: *1677 http2 frame complete pos:0000000001F8049D end:0000000001F8049D
2018/12/18 23:17:42 [debug] 12#12: *1677 GrpcFinish: DEADLINE_EXCEEDED: context timed out
2018/12/18 23:17:42 [debug] 12#12: *1677 http output filter "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 23:17:42 [debug] 12#12: *1677 http copy filter: "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 23:17:42 [debug] 12#12: *1677 http postpone filter "/nestlabs.gateway.v2.GatewayService/Observe?" 00007FFF580357A0
2018/12/18 23:17:42 [debug] 12#12: *1677 http copy filter: -1 "/nestlabs.gateway.v2.GatewayService/Observe?"
2018/12/18 23:17:42 [debug] 12#12: *1677 Failed to send the trailers - rc=-1
2018/12/18 23:17:42 [debug] 12#12: *1677 http finalize request: -4, "/nestlabs.gateway.v2.GatewayService/Observe?" a:1, c:1
2018/12/18 23:17:42 [debug] 12#12: *1677 http request count:1 blk:0
2018/12/18 23:17:42 [debug] 12#12: *1677 http2 close stream 1, queued 0, processing 1, pushing 0
2018/12/18 23:17:42 [debug] 12#12: *1677 http close request
2018/12/18 23:17:42 [debug] 12#12: *1677 http log handler
2018/12/18 23:17:42 [debug] 12#12: *1677 esp log handler: enter: r=0000000002001230, i=0, /nestlabs.gateway.v2.GatewayService/Observe
2018/12/18 23:17:42 [debug] 12#12: *1677 run cleanup: 00000000020020C8
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 00000000020D8520
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 00000000020C8B80
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 00000000020691F0
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 00000000020011E0, unused: 0
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 0000000001BA4BC0, unused: 912
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 0000000001BA5F40, unused: 103
2018/12/18 23:17:42 [debug] 12#12: *1677 post event 00007FE694417A30
2018/12/18 23:17:42 [debug] 12#12: *1677 delete posted event 00007FE694417A30
2018/12/18 23:17:42 [debug] 12#12: *1677 http2 handle connection handler
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 0000000001FFE450, unused: 3120
2018/12/18 23:17:42 [debug] 12#12: *1677 free: 0000000001FF5E90
2018/12/18 23:17:42 [debug] 12#12: *1677 reusable connection: 1
2018/12/18 23:17:42 [debug] 12#12: *1677 event timer add: 42: 10800000:1248456544

**Comment by johnny-y-wang** [comment]
Same issue, can confirm.

**Comment by kh-chang** [comment]
I will start looking into this. Sorry for the delay.

**Comment by johnny-y-wang** [comment]
@kh-chang Just realized it's my fault :) This issue occurs if the gRPC backend address is unresolvable (e.g. a bad DNS name). Accidentally screwed up Kubernetes configuration :/ Maybe a better error message would be helpful here? 

Thanks a lot for your help though!

**Comment by kh-chang** [comment]
@johnny-y-wang Thanks for letting me know!

**Comment by qiwzhang** [comment]
Here is the update on our investigation.  We believe it is caused by Envoy in between your client and ESP.  When your client close the app, the tcp connection is closed,  if there is not Envoy in the middle,  ESP will propagate the tcp connection to the grpc server.   With Envoy,  it is using connection [pool](https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/connection_pooling),   it will keep the connection (between Envoy and ESP) alive, but send RST_STREAM to ESP.  

Yes, ESP doesn't handle RST_STREAM correctly. Now it simply just ignores it.  From the current data flow,  it really NOT easy for ESP to handle RST_STREAM.

Our next action items is:
* to study more about Nginx code to see how easy to hook up ESP code to intercept RST_STREAM signal. 

But just a head up,  we may give up on this effort it if it is too much for us.
