### ISSUE TITLE
INTERNAL: HTTP/2 error code: INTERNAL_ERROR Received Rst Stream (with error code 2)

### ISSUE THREAD

**Issue by clehene** [cloudendpoints/esp#505]
I'm cross posting this from grpc-java 

When I'm using HTTPS LB -> ESP -> gRPC I get these errors 
Full details here https://github.com/grpc/grpc-java/issues/5176

It doesn't reproduce while running ESP locally over SSL.

**Comment by qiwzhang** [comment]
Could you turn on debug by adding --enable_debug [flag](https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L551) In your gke deployment for ESP?

The debug log will be:  /var/log/nginx/error.log inside ESP container.

**Comment by clehene** [comment]
Hey @qiwzhang here's a capture of the error log during a faulty request 
https://gist.github.com/clehene/1e6d7d6a1cd7ae7100c0bb6e78715981

**Comment by qiwzhang** [comment]
Hmm,  somehow between LB and ESP is using http protocol.  It is not using gRPC which should be http2

**Comment by qiwzhang** [comment]
You have to turn on http2 for gRPC to work in your LB.

**Comment by clehene** [comment]
@qiwzhang thanks for taking a look! That could be useful, but could you be more specific.
Concretely, why would HTTPS LB and ESP talk gRPC? the LB exposes SSL and so does ESP/nginx, wouldn't they just use TLS / HTTP/2?

Not sure if you got a chance to read my description on https://github.com/grpc/grpc-java/issues/5176
When I was looking at the wireshark packets I noticed :
> Another difference I noticed is that locally application data packages are
TLSv1.2 Record Layer: Application Data Protocol: http2 while with the LB TLSv1.2 Record Layer: Application Data Protocol: http-over-tls

**Comment by qiwzhang** [comment]
I think you have to configure your LB to use TLS/HTTP2 in order to proxy gRPC, but I am not sure how to do that since I am not familiar with LB.
ESP/nginx is using ssl_port, it can receive both TLS Http1 and TLS Http2. From the Nginx log, ESP is receiving Http1 for your gRPC request from LB.

**Comment by qiwzhang** [comment]
Here is the [doc](https://cloud.google.com/load-balancing/docs/backend-service#protocol_to_the_backends) for Google cloud LB.  It allows you to specify Http2, or Https.  But strangely, you could not specify both.

**Comment by clehene** [comment]
@qiwzhang thank you! You pointed the right direction! 
Overall the docs are highly inconsistent, contradicting themselves.
E.g. https://cloud.google.com/load-balancing/docs/https/:
>To use gRPC with your Google Cloud Platform applications, you must proxy requests end-to-end over HTTP/2. To do this with an HTTP(S) load balancer:
>Configure an HTTPS load balancer.
Enable HTTP/2 as the protocol from the load balancer to the backends.
...
>HTTP/2 to backends is not supported for GKE.

then

> This page shows how to use Kubernetes Ingress and Service objects to configure an HTTP(S) load balancer to use HTTP/2 for communication with backend services. This feature is available starting with Google Kubernetes Engine version 1.11.2.

This https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-http2 is a very recent document. The most important piece is:

```
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"my-port":"HTTP2"}'
```
Not sure if setting the ngxinx ssl port on 443 vs non 443 matters, but I would assume not.
