### ISSUE TITLE
How start ESP with gRPC + Transcoding without Google Cloud Platform integration

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#507]
Hi!

In issue https://github.com/cloudendpoints/esp/issues/501 i wrote about GCP billing cost, but I programming self hosted in-house service API and would not want to have overhead on GCP.

Is it possible, in principle, to launch an ESP in such a way that it does not want to work with a GCP? I found the tutorial (https://github.com/cloudendpoints/esp/blob/master/doc/tutorial.md#running-esp), but there was no example of a gRPC + Transcoding.

**Comment by qiwzhang** [comment]
ESP needs to use Google servicemanagement service to get the service config.  It needs to call Google service control service for checking api-key and sending metrics for dashboard graph.

**Comment by arturgspb** [comment]
Thx, ok, but maybe we can add code for disable Report API call (google.api.servicecontrol.v1.ServiceController.Report)? =)

We talk about it in issue https://github.com/cloudendpoints/esp/issues/501

**Comment by arturgspb** [comment]
@qiwzhang ping

**Comment by qiwzhang** [comment]
Sorry, I missed your question.  ESP code is in open source github.  You can change the code to disable Report call, and build ESP by yourself.

**Comment by arturgspb** [comment]
I hoped you would help me =) I know Java, Python, PHP, JS, but I no work with C++
It seems I'll to have to deal with C ++ in 2019. =)
Well, anyway, thank you so much!

**Comment by qiwzhang** [comment]
There is an easy way to bypass Google service control call.  You can create a HTTP server to mock the Google service control server.  and pass its URL by this [flag](https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L617)

**Comment by arturgspb** [comment]
@qiwzhang Wow! it's perfect!

I came up with a super setting that could help people like me. =)
https://github.com/cloudendpoints/esp/issues/517

**Comment by arturgspb** [comment]
@bochunz thank you. I'll think about this option. 

I want to turn off the Report Call API only for some of my technical services. For most of my api it’s convenient that I can see the method calls charts on Google Cloud Console.

Well, ESP is one love =)
