### ISSUE TITLE
Add Dockerfile for build nginx

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#515]
I have a many troubles when I compile nginx locally on macos. I use virtualbox and install libs and dependencies from doc https://github.com/cloudendpoints/esp/blob/master/doc/build-esp-on-ubuntu-16-04.md

But have errors when nginx start

```
...
INFO:Fetching the service config ID from the rollouts service
INFO:Fetching the service configuration from the service management service
nginx: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by nginx)
Traceback (most recent call last):
```

Now it’s quite difficult to build a project due to numerous nuances and dependencies, especially if I don’t have the old version of ubuntu. I thought it would be convenient if the dockerfile + docker image for the build app.

P.S. I'm not a C ++ developer, and perhaps I'm simply not competent in the simple assembly of this project.

**Comment by qiwzhang** [comment]
Yes, it will be nice if there is a docker image to build ESP.  I will mark this as feature request.

**Comment by qiwzhang** [comment]
@arturgspb I updated this issue: https://github.com/cloudendpoints/esp/issues/507.  Hope it will help you.

**Comment by bfin** [comment]
@arturgspb Same issue here. I wrote this multi-stage dockerfile to build ESP locally for tinkering:

```Dockerfile
FROM ubuntu:16.04 AS build

ENV BAZEL_VERSION=0.21.0

RUN set -ex; \
    apt-get update; \
    apt-get install -y \
        g++ \
        git \
        openjdk-8-jdk \
        openjdk-8-source \
        pkg-config \
        unzip \
        uuid-dev \
        zip \
        zlib1g-dev \
        libtool \
        m4 \
        autotools-dev \
        automake \
        python \
        curl \
    ; \
    rm -rf /var/lib/apt/lists/*; \
    curl -fsSL https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh -o bazel.sh; \
    chmod +x bazel.sh; \
    ./bazel.sh; \
    rm -f bazel.sh

WORKDIR /esp
COPY . ./

RUN bazel build //src/nginx/main:endpoints-server-proxy




FROM debian:stretch-20190506 AS generic

# Copy the ESP runtime Debian package
COPY --from=build /esp/bazel-bin/src/nginx/main/endpoints-server-proxy.deb esp.deb

# Install
RUN set -ex; \
    apt-get update; \
    apt-get install --no-install-recommends -y -q ca-certificates; \
    apt-get -y -q upgrade; \
    apt-get install -y -q --no-install-recommends \
        apt-utils \
        adduser \
        python \
        libc6 \
        libgcc1 \
        libstdc++6 \
        libuuid1 \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    dpkg -i /esp.deb; \
    rm /esp.deb

# Create placeholder directories
RUN mkdir -p /var/lib/nginx/optional; \
    mkdir -p /var/lib/nginx/extra; \
    mkdir -p /var/lib/nginx/bin

# Status port 8090 is exposed by default
EXPOSE 8090

# The default HTTP/1.x port is 8080. It might help to expose this port explicitly
# since documentation still refers to using docker without additional EXPOSE step
EXPOSE 8080

ENTRYPOINT ["/usr/sbin/start_esp"]




# Build more secure ESP docker image running as non-root
# and allow root filesystem as read-only.
FROM generic AS secure

RUN set -ex; \
    rm -rf /var/log/nginx; \
    mkdir -p /var/log/nginx /var/cache/nginx; \
    chown nginx:nginx /var/log/nginx /var/cache/nginx; \
    chmod 777 /var/log/nginx /var/cache/nginx

USER nginx

ENTRYPOINT ["/usr/sbin/start_esp", "--server_config_dir=/home/nginx", "--config_dir=/home/nginx/endpoints"]




# ESP Proxy that gets arguments from env vars
FROM generic AS serverless

COPY ./docker/serverless/env-start-esp.py /

ENTRYPOINT ["/env-start-esp.py"]

```

If you're unfamiliar with multi-stage docker builds, you specify a "target" build like this:
```bash
docker build --target=generic --tag=esp-generic .
docker build --target=secure --tag=esp-secure .
docker build --target=serverless --tag=esp-serverless .
```

These builds have the additional benefit of being much smaller than the official releases because they do not include the build layers.

@qiwzhang I'd submit a PR to include this but I'm still getting my head wrapped around the current build/test processes!

**Comment by qiwzhang** [comment]
if we can pre-build a docker image,  then "docker run" it with -v to mount your local source code into it to build and test ESP, that is a prefer way.

The task are:
1) this docker image used by our Jenkins test may work:  gcr.io/endpoints-jenkins/debian-9:0.10
Someone just need to try it out.  It is include in this [file](https://github.com/cloudendpoints/esp/blob/master/Jenkinsfile#L55). 

2) write a script to "docker run", similar to Envoy [one](https://github.com/envoyproxy/envoy/blob/master/ci/run_envoy_docker.sh)

Our presubmit tests are [here](https://github.com/cloudendpoints/esp/blob/master/script/presubmits)

We can write a new build_esp script which can either run all presubmit tests, or individual test.
