### ISSUE TITLE
Add nginx flag for sampling Service Control API Report Calls

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#517]
I was try known how to less price for local run ESP in issues:
https://github.com/cloudendpoints/esp/issues/501
https://github.com/cloudendpoints/esp/issues/507

@qiwzhang helped me so much with answer https://github.com/cloudendpoints/esp/issues/507#issuecomment-454087910

It's perfect for me now, but it's dropped api requests log totally. It would be nice in future if I could set the percentage of data sampling for the API.

**Comment by qiwzhang** [comment]
If you are using my suggestion in  #507 (comment),  you can do this in your fake service control service.  Your service is just like a proxy,, it decides how many reports to drop and how much to pass on to the Google service control service.

**Comment by arturgspb** [comment]
I known it and use it, but I mean that feature will be useful for ESP as flag

**Comment by qiwzhang** [comment]
If implemented in ESP, it means ESP should know two service-control URLs and split the traffic between two URLs.  I don't think this is the right approach.

**Comment by qiwzhang** [comment]
Am I understanding correctly: you request ESP not sending all Reports, only some sample of them? 
If so,   I don't think we will implement such feature.

**Comment by arturgspb** [comment]
Ok
