### ISSUE TITLE
ESP forwards HTTP1 headers that are not supported by HTTP2 to HTTP2 backends

### ISSUE THREAD

**Issue by MrMage** [cloudendpoints/esp#560]
My backend is logging the following error messages:

```
nghttp2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [connection], value: [keep-alive]
```

This is because the HTTPS Uptime Checks sent via HTTP1.1 by Google Stackdriver Monitoring send a `Connection: keep-alive` header to the backend (verified with ESP's `log_request_headers` flag). According to RFC 7540 (also see https://github.com/nghttp2/nghttp2/issues/887), this header must not be sent:

```
   HTTP/2 does not use the Connection header field to indicate
   connection-specific header fields; in this protocol, connection-
   specific metadata is conveyed by other means.  An endpoint MUST NOT
   generate an HTTP/2 message containing connection-specific header
   fields; any message containing connection-specific header fields MUST
   be treated as malformed (Section 8.1.2.6).
```

ESP should strip this header rather than forward it to HTTP2 backends.

Amendment: According to https://nghttp2.org/documentation/programmers-guide.html,

> HTTP/2 prohibits connection-specific header fields. The following header fields must not appear: "Connection", "Keep-Alive", "Proxy-Connection", "Transfer-Encoding" and "Upgrade". Additionally, "TE" header field must not include any value other than "trailers".

**Comment by qiwzhang** [comment]
I am a little bit confused.  Your backend is serving http2, but "HTTPS Uptime Check" is using HTTP1.1.   
How do you config ESP or Nginx to send downstream HTTP1.1 to upstream http2?
I am not sure if  Nginx is capable  of such protocol translation.

**Comment by MrMage** [comment]
@qiwzhang This is an official feature of Cloud Endpoints: https://cloud.google.com/endpoints/docs/grpc/transcoding. The backend is a custom gRPC service based on HTTP2.

**Comment by qiwzhang** [comment]
I see.  You are using ESP gRPC transcoding.  Thanks.

**Comment by MrMage** [comment]
@qiwzhang does the error report make sense, then?

**Comment by qiwzhang** [comment]
Yes, it is indeed an ESP issue.  ESP should remove more headers here:
https://github.com/cloudendpoints/esp/blob/master/src/grpc/proxy_flow.cc

I will filled a PR soon
