### ISSUE TITLE
Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by srs** [cloudendpoints/esp#567]
When adding Linkerd 2 proxy in front of the ESP, the request returns `400 Request Header Or Cookie Too Large`.

It could be that `large_client_header_buffers 4 32k;` needs to be set in Nginx. 

Anyone else has this problem?

**Comment by whitlockjc** [comment]
The default maximum header size is `8K` so without an nginx configuration to bump that, it's more than feasible.

**Comment by qiwzhang** [comment]
I prefer to do "large_client_header_buffers 16 8k;" so that normal memory consumption is not increased.  I assume each header line do not exceeded 8k.

**Comment by qiwzhang** [comment]
@kh-chang could you help to create a PR for this?  For simplicity, we can just add this line to our nginx config.  It should not have any side effect.

**Comment by kh-chang** [comment]
like adding a flag?

**Comment by qiwzhang** [comment]
I mis-read the nginx config. We should increase buffer size,  not the number of the buffers
we can add an new flag  to specify the buffer size

**Comment by kh-chang** [comment]
The docker presubmit is failing due to:
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by kh-chang** [comment]
We added a flag `--large_client_header_buffers` to make it easier to set it with a custom value.
The change should be available in the next release. 

Make sure to quote the value (e.g. `--large_client_header_buffers='4 32k'`)
