### ISSUE TITLE
How I can config ESP for send default values for integer fields and etc?

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#568]
Hi!

Now if response has integer field with zero value ESP do not send field key in response.
I think it related with https://developers.google.com/protocol-buffers/docs/proto3#default.

I can fix it by ESP config or other?

**Comment by qiwzhang** [comment]
You can try this flag: https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L712

**Comment by arturgspb** [comment]
Thanks!

Param --transcoding_always_print_primitive_fields works good!
