### ISSUE TITLE
Unable to use / as a target for an API path

### ISSUE THREAD

**Issue by adamf** [cloudendpoints/esp#569]
Using this OpenAPI v2 YAML:
```
swagger: '2.0'
info:
  title: Test API
  version: '1.0'
  description: Test API
  contact:
    name: Test API
    url: 'https://api.example.com'
    email: foo@example.com
produces:
  - application/json
host: test.api
paths:
  /:
    get:
      operationId: openapi_server.controllers.default_controller.index
      description: Checks for okay
      responses:
        '200':
          schema:
              type: string
          description: ""
      summary: Get an OK
      x-openapi-router-controller: openapi_server.controllers.default_controller
```

Results in ESP saying:
```
INFO:Refreshing access_token
INFO:Fetching the service config ID from the rollouts service
INFO:Fetching the service configuration from the service management service
nginx: [warn] Using trusted CA certificates file: /etc/nginx/trusted-ca-certificates.crt
2019/03/21 01:08:01[error]1#1: Invalid HTTP template: /
```

If I add additional paths to the OpenAPI spec, those work. I'm not well versed in nginx configuration so I'm not sure how to debug this, but happy to help!

**Comment by adamf** [comment]
Ah, I found https://cloud.google.com/endpoints/docs/openapi/openapi-limitations#operations_on_url_root_path_ which indicates this isn't supported. However, AFAICT, the only way to use Endpoints with container native load balancing is to have the API backend respond with a 200 on / so the health checker will work. I had hoped adding / to the OpenAPI spec would fix that, but perhaps something else needs to be done. The GoogleHC is getting a 404 from ESP in my deployments:

`130.211.2.44 - - [20/Mar/2019:15:33:04 +0000] "GET / HTTP/1.1" 404 200 "-" "GoogleHC/1.0"`

It's unclear how to resolve these issue; I'll try to add another listener on / on the backend service without using OpenAPI to generate that path.

**Comment by adamf** [comment]
Adding `x-google-allow: all` to the top of the OpenAPI 2 file has solved this issue, but it seems odd that this is required. Have I misconfigured the API, or is there an issue in ESP that prevents the google healthchecker from succeeding when requesting / from ESP?

**Comment by qiwzhang** [comment]
Unfortunately, ESP doesn't support root path "/" in its path match component.  

Another way to work around it is to use --requst-path flag 

--request-path=[REQUEST_PATH] \

set it to a path other than "/" in your LB health check setting.

https://cloud.google.com/load-balancing/docs/health-checks

**Comment by adamf** [comment]
Thanks! I'll close this issue out. Note that with the GKE approach to deploying endpoints, the docs recommend you use an `Ingress`, which creates the LB and NEGs for you, which means you don't have control over the LB's health check path at creation time (AFAICT, I could easily be wrong).
