### ISSUE TITLE
"Request blocked due to unsupported error code: 122"

### ISSUE THREAD

**Issue by sgammon** [cloudendpoints/esp#573]
Hello ESP devs,

We've been having some issues using ESP with Cloud Functions, specifically, we think, the Service Control API. For a subset of our traffic, and only on a few API keys at a time (leading us to believe it's related to quota control somehow), we get the following JSON response served as a `500 Internal Server Error`:

```json
{
  "code": 13,
  "message": "Request blocked due to unsupported error code: 122",
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.DebugInfo",
      "stackEntries": [],
      "detail": "service_control"
    }
  ]
}
```

The line of code that produces this error is from ESP, not Nginx:
https://github.com/cloudendpoints/esp/blob/9c50be735adf66180427a9044fffa023a4b06405/src/api_manager/service_control/proto.cc#L1346

So, we're wondering what the error code is, and how we might go about fixing it? Thank you in advance for your help

**Comment by sgammon** [comment]
p.s. the [`Code` payload reference on the Service Control API](https://cloud.google.com/service-infrastructure/docs/service-control/reference/rest/v1/Code) seems to only reference the [standard gRPC status codes](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md), so I am not sure where I might find out what code `122` means, but I am happy to try and debug from our end. thank you again

**Comment by qiwzhang** [comment]
It is documented here

https://github.com/googleapis/googleapis/blob/master/google/api/servicecontrol/v1/check_error.proto#L72

**Comment by qiwzhang** [comment]
We will fix ESP to return error message correctly.  not called it as "unsupported error code"

**Comment by sgammon** [comment]
Thank you @qiwzhang

**Comment by sgammon** [comment]
@qiwzhang, in our case, it seems like the service in question was indeed enabled, for the API key which was passed.

the subject error code here is `API_TARGET_BLOCKED` which elaborates via your link:
"The API targeted by this request is invalid for the specified consumer project."

however, the project was and is enabled in Cloud Endpoints, you can see the traffic being reported here, during March (we've disabled reporting here for now, while we resolve this issue).

any ideas? or am i interpreting the data wrong? thank you again
<img width="379" alt="Screen Shot 2019-03-28 at 4 03 45 PM" src="https://user-images.githubusercontent.com/171897/55198459-47405c80-5173-11e9-9b1e-7f916507e157.png">

**Comment by qiwzhang** [comment]
Let me try to find a Google service control expert to help

**Comment by qiwzhang** [comment]
@sgammon could you provide your project_id your api-key is issued for,  we can check if it is enabled for the service control service?
