### ISSUE TITLE
Local ESP fail to connect to google service

### ISSUE THREAD

**Issue by lamcst** [cloudendpoints/esp#602]
I had set up esp locally. Whenever i try to call esp server, it give me this error message.
`{
    "code": 16,
    "message": "JWT validation failed: Unable to fetch verification key",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.DebugInfo",
            "stackEntries": [],
            "detail": "auth"
        }
    ]
}`
Log from docker
`INFO:Fetching the service config ID from the rollouts service
INFO:Fetching the service configuration from the service management service
nginx: [warn] Using trusted CA certificates file: /etc/nginx/trusted-ca-certificates.crt
2019/05/10 02:06:24 [error] 11#11: www.googleapis.com could not be resolved (110: Operation timed out)
172.17.0.1 - - [10/May/2019:02:06:24 +0000] "GET /v1/ops/telcos/size?key=xxxx HTTP/1.1" 401 223 "-" "PostmanRuntime/7.11.0"
2019/05/10 02:06:54 [error] 11#11: cloudtrace.googleapis.com could not be resolved (110: Operation timed out)
2019/05/10 02:06:54[error]11#11: Trace Request Failed.ERROR: Failed to connect to server.
2019/05/10 02:06:55 [error] 11#11: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2019/05/10 02:06:55[error]11#11: Failed to call https://servicecontrol.googleapis.com/v1/services/xxxx.appspot.com:report, Error: ERROR: Failed to connect to server., Response body: 
[libprotobuf ERROR external/servicecontrol_client_git/src/service_control_client_impl.cc:182] Failed in Report call: Failed to connect to service control`

**Comment by qiwzhang** [comment]
Please try to ping "servicemanagement.googleapis.com" to see if your local DNS can resolve that hostname.

**Comment by qiwzhang** [comment]
@lamcst any update?

It seems that your local ESP could not talk to outside network. It could not talk to 
https://servicemanagement.googleapis.com/v1/services/xxxx.appspot.com/rollouts



for JWT, it could not talk to public key server with this error

JWT validation failed: Unable to fetch verification key"

**Comment by lamcst** [comment]
@qiwzhang 
Thanks for response.
I had ping the "servicemanagement.googleapis.com", it does work.

I miss out the last line of log, now i add it back, hope it helps.

**Comment by lamcst** [comment]
@qiwzhang Thanks!
It is my company wifi network block ESP to google service.
