### ISSUE TITLE
RST_STREAM error if the details is large

### ISSUE THREAD

**Issue by fieryorc** [cloudendpoints/esp#618]
Hi,
  Our service is using ESP to translate JSON request to GRPC and calls our backend server (golang) implementing grpc protocol. In one of the APIs, we send back validation errors as a protobuf error details message and all works fine if the message is small in size. However, when the number of details is large, ESP returns RST_STREAM error. 

I tested various limits and the limit seems to be around 30. Anything more than 30, ESP fails. The detail message itself is very simple containing field, message and the value. 

> curl -X POST http://localhost:9000/v2/accounts/917/products/quan-backup-solution:publish
{
 "code": 13,
 "message": "Received RST_STREAM with error code 2",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "internal"
  }
 ]
}

If there are fewer details, then all works fine.
> curl -X POST http://localhost:9000/v2/accounts/917/products/quan-backup-solution:publish
{
 "code": 3,
 "message": "validation errors",
 "details": [
  {
   "@type": "type.googleapis.com/orbitera.internal.products.v2.ProductValidationError",
   "message": "value must be specified for all supported currencies",
   "field": "Definition.Skus[0].Plans[0].Phases[1].RecurringPrice",
   "value": "CAD",
   "errorType": "PRICE_MISSING_CURRENCY"
  }
}

**Comment by qiwzhang** [comment]
30 bytes?  It seems that the working message is already more than 30 bytes.

**Comment by qiwzhang** [comment]
Which ESP version are you using?

**Comment by fieryorc** [comment]
Not 30 bytes, 30 messages. I tested with the latest (1.33) and still repros. 

Essentially if a details message contains a large string, this happens. I'm not sure the size of the message, but it is <100KB.

**Comment by fieryorc** [comment]
Seems like it is failing around 8K limit..

**Comment by qiwzhang** [comment]
You can try ESP --enable_debug [flag](https://github.com/cloudendpoints/esp/blob/af9836ff91e749ee66e64f73f70f95de7bd1d2ba/start_esp/start_esp.py#L551)

To run the traffic.   the log is inside the ESP container in /var/log/nginx/error.log.

Could you post the log for me?

**Comment by fieryorc** [comment]
Here you go: https://paste.googleplex.com/5504360203157504

**Comment by qiwzhang** [comment]
You may have run into this grpc limit "grpc.max_metadata_size".  I googled it. There is this [discussion](https://groups.google.com/forum/#!topic/grpc-io/FoLNUJVN4o4)

I am still not sure if client or server can change it.   ESP is the grpc client,  your is the server.

I will take a look the ESP debug trace.

**Comment by qiwzhang** [comment]
You may want to check out this [issue](https://github.com/grpc/grpc-go/pull/2084). It shows you how to to set max_metadata_size in golang.

**Comment by qiwzhang** [comment]
ESP debug indicates that the error is from your grpc-server.

**Comment by qiwzhang** [comment]
I think you run into "grpc.max_metadata_size" limit. It seems the default is only 8 KB.  ESP (as grpc-client) does not set it.   But I believe if your server can set it, it should work.

**Comment by fieryorc** [comment]
Ran with the following settings:

	s := grpc.NewServer(grpc.MaxSendMsgSize(math.MaxInt32), grpc.MaxHeaderListSize(math.MaxInt32), grpc.MaxRecvMsgSize(math.MaxInt32))

Still same error. Error log:
https://paste.googleplex.com/4802307919183872

**Comment by fieryorc** [comment]
If I use grpc-gateway, I don't get any error. It is translating fine.

**Comment by qiwzhang** [comment]
I increased ESP channel size to INT_MAX.  It works.

**Comment by fieryorc** [comment]
Thank you for super fast response. I'll wait for the docker image to be released to test the fix. Any idea when that will be released?

**Comment by qiwzhang** [comment]
This week ESP release should have this fix.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/releases/tag/v1.34.0
