### ISSUE TITLE
Add include to nginx-auto.conf.template for http {} section

### ISSUE THREAD

**Issue by peter-fe** [cloudendpoints/esp#630]
In regards of tracking calls through the system it would be a great deal if it's possible to define the log contents & format of the Nginx backed ESP.

Currently on GKE it is possible to add some kind of correlation to the logs created by the service control part (not sure how you actually call that), by adding headers with --log_request_headers=foo,bar that can be used for that.

That's really a nice feature but leaves still some blind spots to track the calls progressing through the system. We use tracing as well, but this is more for debugging or tracking some dedicated error cases by going through the logs by using a correlation id. (and there is a good chance that there is no tracing for that single call)

Especially in more complex setups as GKE + Istio + ESP + multiple back end services.

1. In out use case we added the request_id to the service_control/api related part of the ESP logs by using --log_request_headers x-request-id.
2. This almost gives us the expected behavior as the istio-ingressgateway is creating this id on the first contact of the call to the system and exposing it in the access log.
3. The istio-proxy (sidecar) is picking that up as well and puts it into the access log.
4. The next hop (or at least for the sc/api part) is also working an is adding this request_id to the log file.
5. Next in the line is the ESP container on GKE itself, here the plain Nginx log format kicks in with no option to adjust (without going into complete self managed Nginx.conf), so this is the blind spot currently.
6. Last in the line is our app behind the ESP, here we have that request_id again.

We have seen that there are already includes used in the nginx-auto.conf.template, but sadly not on the "http {}" section, so no chance to inject a custom log format to get picked up by the Nginx.

It would be a great option if it is possible to use includes on that layer as well like the common 

> \#\# Include all VirtualHosts.
> include /etc/Nginx/conf.d/*.conf;

or some similar path. That way someone can stay in the managed/provided Nginx.conf with additional flexibility of adjusting by using config maps.

**Comment by qiwzhang** [comment]
Please help me to understand your requirements: 

You want to log request_id to track a specific request in a distributed system,  why doesn't the flag "--log_request_headers=request_id" help?  It will write a stackdriver log entry with request_id.

How will adding a nginx conf include help?  what kind of include will you add?  How are you going to copy your custom include files into esp containers

**Comment by peter-fe** [comment]
@qiwzhang, thank you for your detailed questions I'll try to answer them as clear as possible to describe our use case.

Basically our topology looks like this:

![arch](https://user-images.githubusercontent.com/22496291/59130768-a212e300-8970-11e9-8423-1b5c4e58cecb.png)

In the past we had several errors where the request died within the esp container, because of service control errors and we had a hard time correlate these errors back to find out which calls where effected, surely it's possible to try matching by timestamps but at 200+ rps that's more like a lucky shot and the logs are all in place just a tiny bit of information is missing.

Setting the --log_request_headers option was a very big improvement in that regard, but at first we where a bit puzzled why we don't see that in the ESP container logs as well (later it was clear because the logs are created by the Nginx itself).

Never the less it would streamline the whole process if that information would be available and it seems that the change needed for that is quite small and without high impact regarding risk.
We won't go for a completly self managed Nginx.conf as we are not sure how to cope with the regular updates and maybe changes in the template, so includes look way more manageable. 

Regarding your question where we would place the include:
I think adding something like **include /etc/Nginx/conf.d/*.conf;** in nginx-auto.conf.template, just below the mime.types include or at the end of the http {} section would do the trick and seems quite common in nginx.conf samples I've seen. (e.g.: for adding virtualHosts)

We are running on GKE so the easiest way to add that extra config would be to use config maps and mount them into the right folders with volumes, I assume.

best
Peter

**Comment by qiwzhang** [comment]
Will this work for you?

**Comment by peter-fe** [comment]
@qiwzhang 

That worked perfectly!

Just gave it a try with your changed template + custom log_format mapped to /etc/nginx/conf and selecting this custom format with the access_log config parameter.

![esp-k8s-deployment](https://user-images.githubusercontent.com/22496291/59145080-8a267800-89df-11e9-8160-09727f7432f0.jpg)

And the log output looked perfect!
![nginx-log](https://user-images.githubusercontent.com/22496291/59145090-9f030b80-89df-11e9-921d-26d3a656c688.jpg)

Thank you very much for the adjustment!
Would be great if it makes it into the release!

best,
Peter
