### ISSUE TITLE
use more_set_headers module to simply nginx config

### ISSUE THREAD

**Issue by qiwzhang** [cloudendpoints/esp#632]
raised by https://github.com/cloudendpoints/esp/issues/473#issuecomment-500026156

**Comment by qiwzhang** [comment]
This module is not part of Nginx, need to install it separately. Two options, 1) wait for ESP [Nginx](https://nginx.googlesource.com/nginx/) to add it in.  Or 2) Change ESP bazel dependencies to install it.

Hi @PiotrSikora do you have plan to include more_set_headers module into this [Nginx](https://nginx.googlesource.com/nginx/) ?

**Comment by PiotrSikora** [comment]
No plans, sorry. You can always add this module directly in ESP, though.

But I don't think that pulling this module to save a few lines in configuration is worth the trouble.

**Comment by qiwzhang** [comment]
Thanks @PiotrSikora. Agreed that it is not worth the trouble.
