### ISSUE TITLE
[DNS] nginx does not re-resolve upstream server destination

### ISSUE THREAD

**Issue by xavier-re** [cloudendpoints/esp#636]
Hello,
I run google cloud end point/ESP on debian stable (stretch) 
ii  google-cloud-sdk                251.0.0-0                      all          Utilities for the Google Cloud Platform
ii  endpoints-runtime               1.35.0                         amd64        Google Cloud Endpoints Runtime  .  .  A Google Cloud

We have the following setup 
internet -> ALB1 -> ESP running on ec2 -> ALB2 -> backend api

when we change the ALB2, ips changes and the ESP cant connect anymore
it says
2019/06/21 14:33:26 [error] 20449#20449: *39048 upstream timed out (110: Connection timed out) while connecting to upstream
I can verify with tcpdump that the ESP connect to the old ip and doesnt re-resolve the domain name. It then fails to answer request, and it's not unhealthy either, since /healthz is answering correctly.
I tried using the valid=30s parameter to the resolver option (which doesnt look like it is applied anyway), no dice.
Otoh I see tons of re-resolve for servicecontrol.googleapis.com and other google urls.
attached are the config file, 
do you have any advice ?
Is it fixable ?

[nginx.conf.txt](https://github.com/cloudendpoints/esp/files/3316496/nginx.conf.txt)
[endpoints-nginx.conf.txt](https://github.com/cloudendpoints/esp/files/3316497/endpoints-nginx.conf.txt)

[server_config.pb.txt](https://github.com/cloudendpoints/esp/files/3316495/server_config.pb.txt)

thanks.

**Comment by qiwzhang** [comment]
You may want to read [this](https://distinctplace.com/2017/04/19/nginx-resolver-explained/)

**Comment by qiwzhang** [comment]
@xavier-re Any update on this issue? Otherwise I will close it.

**Comment by qiwzhang** [comment]
ESP is using free version of Nginx.  It only resolves DNS once. Your case requires its Discovery feature from the pay version of Nginx plus.
