### ISSUE TITLE
Support extracting JWT without "Bearer" prefix

### ISSUE THREAD

**Issue by teb0w** [cloudendpoints/esp#652]
Hi,

ESP doesn't support extracting JWT from header in this format : `Authorization: "<JWT token>"`

It would be great to be able to validate it as it will make it compatible with [Actions On Google](https://developers.google.com/actions/reference/rest/verify-requests). 

My suggestion: if "Bearer" is not found in the Authorization header, take the full header value as a JWT, if the format is valid, instead of rejecting the request. 

[Related stackoverflow question](https://stackoverflow.com/questions/57145885/non-oauth2-jwt-validation-with-google-cloud-endpoints/57154619).

Does this make sense?

**Comment by qiwzhang** [comment]
It makes sense. Mark it as a feature request.
