### ISSUE TITLE
--cors_allow_origin args to esp docker container not applied correctly

### ISSUE THREAD

**Issue by paultop6** [cloudendpoints/esp#663]
I have been passing in the ESP_ARGS environment variable to the docker container on startup with the following args; --cors_preset=cors_with_regex,--cors_allow_origin_regex=^https?:\/\/([\w\d]+\.)?example\.com$

After the OPTIONS query is followed by something like POST, the Response header fields for access-control-allow-methods and access-control-allow-origin appear to be doubled up.  Here is the response to a POST header when the request URL is http://dev.example.com:

access-control-allow-methods: GET, POST,GET, POST, PUT, PATCH, DELETE, OPTIONS
access-control-allow-origin: http://dev.example.com,http://dev.example.com

The browser will not allow more than on origin and the response payload is blocked.

**Comment by qiwzhang** [comment]
I think it is possible that your backend HTTP server already supports CORS.  It already adds access-control-allow-origin: http://dev.example.com header.  Then at ESP(Nginx),  it will add another one.

If your backend supports CORS (most likely it also handles OPTIONS calls), then you should not setup ESP with --cors_preset flags.   In your OpenAPI spec, you should set allow_cors=true as followings
```
x-google-endpoints:
- name: "API_NAME.endpoints.PROJECT_ID.cloud.goog"
  allowCors: True
```

It is documented [here](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions)

**Comment by paultop6** [comment]
> I think it is possible that your backend HTTP server already supports CORS. It already adds access-control-allow-origin: http://dev.example.com header. Then at ESP(Nginx), it will add another one.
> 
> If your backend supports CORS (most likely it also handles OPTIONS calls), then you should not setup ESP with --cors_preset flags. In your OpenAPI spec, you should set allow_cors=true as followings
> 
> ```
> x-google-endpoints:
> - name: "API_NAME.endpoints.PROJECT_ID.cloud.goog"
>   allowCors: True
> ```
> 
> It is documented [here](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions)

Yep that was exactly it.  Thanks for the tip.
