### ISSUE TITLE
Question: Any work on an ESP istio adater?

### ISSUE THREAD

**Issue by srs** [cloudendpoints/esp#668]
Hi. Just wondering if anyone are working on an ESP istio mixer adapter?

**Comment by qiwzhang** [comment]
Could you be more specific on this adaptor?  What info will be passed to Istio  or vis verse?

**Comment by srs** [comment]
I was thinking of an Istio mixer adapter that does the following for each configured API call:

* Checks the policies using service-management API's.
* Checks JWT token defined in OpenAPI or gRPC service description.

Pretty much what ESP does today but instead of placing ESP as a sidecar it would be invoked as a Istio mixer adapter if Istio is running as a sidecar.

Apigee has something like this.

**Comment by qiwzhang** [comment]
I see.  Then we don't any work for this, and neither in the future in our road map.
