### ISSUE TITLE
Could we get a release soon?

### ISSUE THREAD

**Issue by sgammon** [cloudendpoints/esp#671]
We love ESP and there are some fixes in `master` that we need, but the latest image (`1.36.x`, I believe), doesn't have them. Could we get a release cut soon?

It would be helpful to know the release schedule for ESP, if there is one, so we can align our work with it downstream. Just a friendly suggestion, we love ESP :)

**Comment by qiwzhang** [comment]
Thanks for the request.  We were busy fixing ESP crashes found from our E2E tests.  Now they are fixed, and release qualification tests are still in progress, I will try to make a ESP release today after they are completed.

In general, we try to make ESP release every 2 weeks if there are any new features or bug fixing changes.

**Comment by qiwzhang** [comment]
https://github.com/cloudendpoints/esp/releases/tag/v1.37.0

**Comment by sgammon** [comment]
@qiwzhang thank you, you guys are always so fast! much appreciated 😄
