### ISSUE TITLE
Allowing mulitple origins

### ISSUE THREAD

**Issue by PaulMazzuca** [cloudendpoints/esp#674]
Does the ESP support multiple origins for CORS requests?

I set the --cors_allow_origin option to "origni1,origin2" and it looks like the ESP is sending both of the origins in the preflight request rather than just the one that is applicable. Maybe I am wrong to believe that the spec should support multiple origins, but I thought I might ask for clarification.

**Comment by qiwzhang** [comment]
You may have to use cors_preset == cors_with_regex.  Please checkout this [doc](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp).

**Comment by PaulMazzuca** [comment]
Thanks, that worked!
