### ISSUE TITLE
Identity resolution is insufficient in Google Compute Engine

### ISSUE THREAD

**Issue by farmdawgnation** [cloudendpoints/esp#675]
When talking to an IAP-secured backend that requires authentication, the [url used to resolve identity metadata](https://github.com/cloudendpoints/esp/blob/0c4e43e5547d2a528111480b956619deec37b6a3/src/api_manager/fetch_metadata.cc#L34-L36) seems to work fine when ESP is running inside Cloud Run, but it is insufficient when ESP is running in Google Compute Engine.

In Google Compute Engine the URL used produces a JWT token that lacks the `email` claim. This results in IAP sending back the following error when you attempt to send your request through ESP:

```
Invalid IAP credentials: JWT 'email' claim isn't a string
```

I replicated the issue manually by pulling the JWT token the identity endpoint creates and manually using it against my IAP-secured app.

This can be fixed by changing the lines referenced to:

```
// URL path for fetch instance identity token
const char kMetadataInstanceIdentityToken[] =
    "/computeMetadata/v1/instance/service-accounts/default/identity?format=full&audience=";
```

This will return the _full_ JWT payload. I've confirmed that this new payload generated from this modified url works correctly if I make a request against my IAP-secured application manually.

This is blocking some work we're doing so if we could get a fix to this and updated docker images deployed quickly, that would be very helpful.

**Comment by qiwzhang** [comment]
I will work on it. Thanks for raising the issue.

**Comment by TAOXUY** [comment]
https://github.com/cloudendpoints/esp/pull/676
