### ISSUE TITLE
Crash when disabling Service Control

### ISSUE THREAD

**Issue by sgammon** [cloudendpoints/esp#684]
Hello there ESP authors,

We hit a nasty bug today. While mitigating some issues with credentials and the Service Control API, we tried to shut service control off, with `service_control off`.

However, this caused the Nginx worker to begin repeatedly crashing with `SIGCHLD`. After some testing, we discovered it's only possible to shut Service Control off if you also shut off `api_authentication`. It's fine if Service Control is required for API authentication, but if that's the case, it should either produce an error or just shut off API authentication if Service Control is unavailable, rather than crashing.

Here's the config that breaks:
```
endpoints {
        on;
        server_config /etc/nginx/server_config.pb.txt;
        metadata_server http://169.254.169.254;
        cloud_tracing off;
        service_control off;
        api_authentication default;
}
```

Here's the config that works:
```
endpoints {
        on;
        server_config /etc/nginx/server_config.pb.txt;
        metadata_server http://169.254.169.254;
        cloud_tracing off;
        service_control off;
        api_authentication off;
}
```

We've confirmed this crash on ESP range `1.35.x` > `1.38.x`.

**Comment by qiwzhang** [comment]
In current design, api_authentication requires service_control.  In theory, it should not, but code structure wise, it is required.   So it doesn't make sure to have the first config.  It should be the same as the second one.

I made this change to test your config.  https://github.com/cloudendpoints/esp/pull/686

It did not crash on me.

**Comment by sgammon** [comment]
Hey @qiwzhang,

Understood, but then could a warning be emitted? I don't then exactly know what's crashing, because it only crashes when `service_control off;` is mentioned and `api_authentication default;` is present.

I can try to provide you with some context:
- Our config file, if I can share privately
- We use a Service Key, rather than the metadata server, if that at all affects things

Let me know if I can help, and thank you for your quick response.

**Comment by qiwzhang** [comment]
Just read the ESP code again, I think it is possible that jwt_auth is on while service control is off.   We never test it.   Will use this use to test it and make sure it works.

**Comment by qiwzhang** [comment]
Actually,  we already have a "t" [test](https://github.com/cloudendpoints/esp/blob/master/src/nginx/t/service_control_disabled.t) covering this feature.   It is exactly "service_control off"  but jwt_auth is still on to verify jwt tokens.

**Comment by qiwzhang** [comment]
@sgammon  could you debug your case with flag --enable_debug and gave me the core files and nginx error logs.   They are all inside ESP container.  core files in /tmp and log files in /var/log/nginx

**Comment by qiwzhang** [comment]
@sgammon any update?  Otherwise, I will close this issue.

**Comment by sgammon** [comment]
@qiwzhang it will take me a few days to get back to this, i'm out of town at the moment. feel free to close in the meantime and i can reopen with more context
