### ISSUE TITLE
"Allow cors: true" not working (error 500)

### ISSUE THREAD

**Issue by tafm** [cloudendpoints/esp#697]
Im running at cloud run:
gcr.io/endpoints-release/endpoints-runtime-serverless:1.30.0
![insomnia](https://user-images.githubusercontent.com/12813195/65074822-f5330380-d96b-11e9-8ad9-19620bafc1cb.png)

**Comment by qiwzhang** [comment]
Could you try to run latest ESP image by only using tag ":1"?

e.g. gcr.io/endpoints-release/endpoints-runtime-serverless:1

**Comment by tafm** [comment]
same error, i've tried with tag 1 and 1.40.0

**Comment by qiwzhang** [comment]
Could you check Stackdriver log to get hints?

**Comment by qiwzhang** [comment]
In Cloud Console page; select Logging->Logs Viewer;  Filter by "Produced API" -> SERVICE_NAME

**Comment by qiwzhang** [comment]
From your title, it seems that you are using following in  OpenAPI service config

`x-google-endpoints:
- name: "API_NAME.endpoints.PROJECT_ID.cloud.goog"
  allowCors: True`

If so, please make sure your backend supports CORS, e.g.  OPTIONS http calls.  This flag just tells ESP to forward the OPTIONS calls to your backend.

**Comment by qiwzhang** [comment]
If your backend doesn't support CORS, e.g. gRPC service, then you have to config ESP (Nginx) to support it.   Please read this [doc](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp)

**Comment by tafm** [comment]
![image](https://user-images.githubusercontent.com/12813195/65085505-b8273b00-d984-11e9-98e7-9f426a24d998.png)

im using:

```
x-google-endpoints:
  - allowCors: true
    name: voxia-public-api-esp-agskifmnha-uc.a.run.app
```
running the backend also on cloud run, and the cors config works without esp

**Comment by qiwzhang** [comment]
I see,  you run into a known issue; ESP could not route OPTIONS calls to the backend specified by x-google-backend.

You have to config ESP to handle CORS by following this [doc](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp)

There is a section about CORS in this Endpoint for Cloud Run [doc](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run)

**Comment by levibn123** [comment]
I've run in this same issue.

I also tried to handle CORS in ESP following [this doc](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp)

But i can't see how this can be accomplished deploying ESP on Cloud Run. Not even at the Endpoints for Cloud Run [doc](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-run) we have details about how to pass the arguments from  [this doc](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp) that handles the CORS direct on ESP to the Cloud Run.

**Comment by qiwzhang** [comment]
Here is the command:

`
gcloud beta run services update CLOUD_RUN_SERVICE_NAME \
   --set-env-vars="^|^ENDPOINTS_SERVICE_NAME=YOUR_SERVICE_NAME|ESP_ARGS=--rollout_strategy=managed,--cors_preset=basic" \
   --platform managed \
   --project ESP_PROJECT_ID
`

ESP flags have to be passed into the Cloud Run as ESP_ARGS environment variable
