### ISSUE TITLE
Is it possible to specify multiple backends in the start up arguments?

### ISSUE THREAD

**Issue by nico-kuzak** [cloudendpoints/esp#698]
Hi,

When initializing my Kubernetes Deployment, I have 3 containers - 1 is hosted on 8080, 1 is on 8090, and the 3rd is the ESP on 8081. Right now, as part of the arguments, I have 
          "--http_port=8081",
          "--backend=127.0.0.1:8080"

Is it possible to host a second backend (8090)?

**Comment by qiwzhang** [comment]
Sorry, multiple backend is not supported. 

ESP usually is deployed as side-car proxy; one for each backend.   

In your case, I think it will be more nature to have two deployments; and each deployment has its own esp container.
