### ISSUE TITLE
Enable SSL for Google Enpoint ESP, but client side SSL certificate validate fail

### ISSUE THREAD

**Issue by rongbino** [cloudendpoints/esp#699]
I follow this document to enable the SSL for my google endpoint. 

https://cloud.google.com/endpoints/docs/openapi/enabling-ssl

But after that, during I want to test it in `POSTMAN` or request through code side with `HTTPS`.  I always got `SSL certificate validate fail`.
In POSTMAN, I must go to preference -> General -> SSL certificate validate , and disable it.
In python code side, must with parameter verify=False.

How can I make it verify successful??  
Should I upload the media CA certificate to ESP ?  How to do that?

thanks

**Comment by qiwzhang** [comment]
Were you using link to generate a self-signed certificates?  If so,  you may have to set "subject" in the cert to your DNS name by using this flag for openssl

-subj "/CN=YOUR-DNS"'

If you follow the link, it shows how to upload the cert files into ESP container by using "Kubernetes secret "

**Comment by rongbino** [comment]
@qiwzhang I use the certificate from DigitCert.  I payed for it.
The domain name like *.example.com

**Comment by qiwzhang** [comment]
I am not SSL expert.  After google this error,  I found this [link](https://stackoverflow.com/questions/46604114/python-requests-ssl-error-certificate-verify-failed)

Maybe you can use [link](https://www.ssllabs.com/ssltest/analyze.html?d=hcaidcs.phe.org.uk) to test your ssl enabled endpoints

**Comment by qiwzhang** [comment]
You can use this "ssl_protocols" [flag](https://github.com/cloudendpoints/esp/blob/f9e2b7ed716876d5533fde2d91694b9f6a2ceed0/start_esp/start_esp.py#L836) to specify ssl versions.
