### ISSUE TITLE
secure ESP image with custom nginx config

### ISSUE THREAD

**Issue by rvillane** [cloudendpoints/esp#702]
Hello, I wanted to use the secure image, but reading documentation at: https://github.com/cloudendpoints/esp#secure-image the wording is confusing.

It says:

> You can switch to use the secure images if the followings are satisfied:
> 
> - Nginx is not listening on ports requiring root privilege (ports < 1024).
> - **Not use custom nginx config**. The server_config path is hard coded to /etc/nginx/ folder in the custom nginx config. The secure image moved the server_config to /home/nginx. Please modify your custom nginx config before using the secure image.

However, the second condition, is not clear if custom nginx config file just doesn't work with the ESP secure image or if is allowed as long as the config file has server_config pointing to /home/nginx.

please advice

**Comment by qiwzhang** [comment]
Sorry for the confusion.  If your nginx config file has:
`server_config /home/nginx//server_config.pb.txt;`

The secure image can be used.  I will update the doc.

Thanks
