### ISSUE TITLE
Getting error from ESP while trying to upload a file via gRPC using transcoding

### ISSUE THREAD

**Issue by aashish004** [cloudendpoints/esp#720]
Seems like ESP has trouble transcoding bytes.
```
das-cc44fd4b7-lqvjv esp] [libprotobuf ERROR external/protobuf_git/src/google/protobuf/wire_format_lite.cc:611] String field 'google.rpc.Status.message' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.  
[das-cc44fd4b7-lqvjv das] INFO:services.das: 
[das-cc44fd4b7-lqvjv esp] 10.160.15.245 - - [18/Oct/2019:13:07:53 +0000] "POST /v1/upload HTTP/1.1" 400 228 "-" "PostmanRuntime/7.15.2" 
[das-cc44fd4b7-lqvjv esp] [libprotobuf ERROR external/protobuf_git/src/google/protobuf/wire_format_lite.cc:611] String field 'google.protobuf.Value.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to 


service DocumentService{
    // upload Enity with document
    rpc uploadFileStream(stream DocumentStreamRequest) returns (DocumentStreamResponse){
        option(google.api.http) = {
            post: "/v1/upload"
            body:"*"
        };
    }
}


message DocumentStreamRequest {
    bytes data = 1;
}


message DocumentStreamResponse {
    string requestId = 1;
    string message = 2;
}
```

**Comment by qiwzhang** [comment]
For streaming: your request body should be wrapped with json [].   Essentially, your request body should look like this:

[
{ "data": "binary-bytes"},
{ "data": "binary-bytes"},
{ "data": "binary-bytes"}
]

Here is our [test](https://github.com/cloudendpoints/esp/blob/master/src/nginx/t/transcoding_streaming.t#L104) for testing streaming transcoding. 

I like you to capture the incoming request to ESP by turning on --enable_debug flag.
And get the error log inside ESP container /var/log/nginx

**Comment by qiwzhang** [comment]
Another possibility is that your descriptor file is wrong.  ESP is using google.prc.Status and google.protobuf.Struct to decode your JSON, it may indicate your Descriptor file you provided to CLI "gcloud endpoints service deploy" is wrong.  

You can verify it by using "gcloud endpoint configs describe" to download your service config, and check your request message type for your uploadFileStream method.
