### ISSUE TITLE
Add NGINX keepalive_timeout flag to ESP startup option

### ISSUE THREAD

**Issue by jianhe25** [cloudendpoints/esp#726]
Google Cloud Load Balancer suggests backend server such as NGINX should change their keepalive_timeout option to 10 minutes to allow load balancer to keep the TCP session alive. See 
suggestion https://cloud.google.com/load-balancing/docs/https/#timeouts_and_retries here.

However ESP startup options doesn't include **keepalive_timeout** option. We have to use a custom NGINX config just to change **keepalive_timeout** parameter. 

Is it possible to add keepalive_timeout to ESP startup options, so we don't have to change it through custom NGINX config?

To be clear, the option is [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout)

This feature should be a common ask to deploy a scalable service in GCP if customer use both Cloud Endpoints and Cloud Load Balancer.

**Comment by qiwzhang** [comment]
It is a legal request.
