### ISSUE TITLE
Add mapping streaming APIs to newline-delimited JSON streams

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#728]
Hi! 
Please consider adding feature newline-delimited JSON streams like in https://github.com/grpc-ecosystem/grpc-gateway

Example exists in https://github.com/grpc-ecosystem/grpc-gateway/issues/581

This would be useful if api return 100k + lines of statistics on advertising objects without loading everything into memory. =) I really want to use the protocol for exchanging such data, but now, unfortunately, I can’t. Of course, there may be problems with the performance of serialization and deserialization, I am ready to discuss this, maybe it is possible to solve the problem differently.

In general, I would like to have api based on the protocol of buffers, use authorization check at the esp level, also in some api sometimes it is necessary to give a large flow of data (we usually have statistics), while from the external system I already getting stream with 100k + CSV for one request time ( for example Google Ads) and I want to immediately redirect them to the output stream, possibly with minimal processing and json mapping. I don’t want to save data to a cloud guard or something like that and give a link to the data. I want to immediately serialize the answer. Certainly in Google it is already somehow decided, maybe you can tell how to do it correctly from the point of view of Google?

Thank you in advance!

**Comment by qiwzhang** [comment]
ESP is using grpc translation code in this [repo](https://github.com/grpc-ecosystem/grpc-httpjson-transcoding).  Could you file an issue there?   Once it is implemented there, we can add a flag to enable it in ESP.

**Comment by arturgspb** [comment]
Thx a lot! I will wait for a decision!
