### ISSUE TITLE
Problem using ESP with Istio proxy (non-sidecar ESP)

### ISSUE THREAD

**Issue by srs** [cloudendpoints/esp#731]
I have been using Endpoints for a long time now, but constantly running into one problem. When doing transcoding everything works fine with the following two setups:

- ESP as a sidecar to gRPC service.
- ESP as a sidecar to gRPC service with Istio proxy.
- ESP --> gRPC service (ESP and gRPC service as different services)

But with the following setup it fails:

- ESP --> gRPC service with Istio
- ESP with Istio --> gRPC service with Istio

It fails with the following error: `Received RST_STREAM with error code 1`. But only when sending a payload as JSON to the ESP. If it has on payload, everything works fine.

And this occurs with Enovy and Linkerd too. Not just Istio. 

I found out that if the content-length header is removed form the payload between the services it will work, but for me that involves having a proxy in between that fixes some headers on the way. 

Any ideas here? Anyone experience the same problem?

**Comment by qiwzhang** [comment]
There are many libraries handling grpc.  
ESP:   nginx/http2 for downstream,  grpc_clint_lib for upstream
Envoy (Istio/proxy):  envoy/http2 for both upstream and downstream.

It must be some incompatibility between these http2 code. 

We can try to use tcpdump in different sections to see which one cause the problem.

**Comment by srs** [comment]
I can do a dump here in different scenarios and try to figure out the differences. Will add updates to this task.
