### ISSUE TITLE
Api gateway for Microservices with Extensible Service Proxy

### ISSUE THREAD

**Issue by shayaanmohit** [cloudendpoints/esp#732]
### Inputs

For example, we have a few services.

1. Account service
2. Product service
3. Payment service

Each service is a separate Google Cloud Function. 
Each service has its own HTTP API. For example, the account service has: 

1. https://REGION-FUNCTIONS_PROJECT_ID.cloudfunctions.net/account/sign-up
2. https://REGION-FUNCTIONS_PROJECT_ID.cloudfunctions.net/account/sign-in
3. https://REGION-FUNCTIONS_PROJECT_ID.cloudfunctions.net/account/reset-password
4. etc

Each service has its own swagger documentation endpoint `/docs`.

### Question

How can I make my Cloud Functions private (without public access) and place them behind some API Gateway? I need to have ability to proxy my cloud functions (like reverse proxy).

**Comment by qiwzhang** [comment]
You can check out this [document](https://cloud.google.com/endpoints/docs/openapi/get-started-cloud-functions).

You can deploy ESP as API-gateway in Cloud Run to proxy requests to your functions.  Make your functions only accessible from ESP proxy.   The bottom of that doc has instructions for that.

**Comment by qiwzhang** [comment]
This [article](https://medium.com/google-cloud/secure-cloud-run-cloud-functions-and-app-engine-with-api-key-73c57bededd1) describes in detail on how to use ESP to enforce api-key to access your service.
