### ISSUE TITLE
Use OAuth flow to generate a JWT for end users.

### ISSUE THREAD

**Issue by mcharsley** [cloudendpoints/esp#738]
See https://plus.google.com/u/0/104036430843977848781/posts/VJC1E1j4ftn for the results of about a week's desperate searching

**Comment by qiwzhang** [comment]
I coped the content here from the link:

A brain dump of what I've spent the last week learning, partially in case it's useful to anyone else, partially as a reminder to myself in case I have too much brandy butter over the Christmas break.

Cloud IAP uses OAuth for authentication
Cloud endpoints uses JWT.

OAuth is a way for me to give BobsEmailApp access to my gmail data. It involves Bob setting up a client ID (so even if the token leaks, EvesEmailApp can't use it to access my data), and asking for specific scopes associated with that client (so the app can access my email, but not my Drive data).

Ideally OAuth involves Bobs server talking directly to the authentication server via redirection URLs, but there's a reluctantly-supported manual approach you can use so you can use cUrl to make API calls from the command-line. See https://cloud.google.com/iap/docs/authentication-howto

JWT in contrast is a single string containing 3 Base64-encoded JSON objects concatanated together. The second object contains useful data, the third object contains a signature verifying the contents of the second, and the first just contains the details of which signature method was used to generate the third.

The second object can contain fairly arbitrary data, but it almost always contains:
 - the issuer: which organisation/server has verified the token, so you can get their public key to verify the signature
 - the audience: which purpose the token was issued for. So e.g. if the token was issued for Gmail, then you can't use it for Drive
 - some userId (typically email) identifying the user.

Cloud's has lots of documentation on how to use JWTs, but it's remarkably hard to find out how to generate a token for e.g mcharsley@google.com. Plenty of stuff on how to generate them for service accounts, but not personal ones.

The secret that no-one appears willing to come out and say is that an OAuth id_token is a JWT. And the JWT's audience field is set to the OAuth ClientID. So to call into a Cloud Endpoint as yourself, you just need to
a) set up an OAuth client in your project (of type other)
b) add the resulting clientId as an acceptable JWT audience in your Endpoint configuration
c) follow the IAP authentication how-to to manually get a id_token and store it in an environment variable TOKEN
d) call your API with curl --header "Authorization: Bearer $ID_TOKEN"

**Comment by nareddyt** [comment]
I'll take a look at this next week and see if we can add this to [our official docs](https://cloud.google.com/endpoints/docs/openapi/authentication-method). Thanks for sharing the post.

**Comment by nareddyt** [comment]
The only improvement in our docs is to explicitly state that Google identity tokens are JWTs. This is already suggested in the following articles:
- https://cloud.google.com/endpoints/docs/openapi/authenticating-users-google-id
- https://developers.google.com/identity/sign-in/web/backend-auth

But it won't hurt to explicitly state that in our cloud endpoints doc (the first link above).
