### ISSUE TITLE
Access-Control-Max-Age Question

### ISSUE THREAD

**Issue by HN-JHOFF** [cloudendpoints/esp#739]
Perhaps this is a question, but kinda feels like an issue.  I have a serverless project where the backend is google cloud functions.  The front end is a basic Angular SPA app and in between I use cloudendpoints / esp to wrap the cloud functions so I can specify a custom domain.  I am using allowCors: true in the esp and setting the response headers I want on the cloud function backend.  It all "works", but no matter what I do I cannot get the Access-Control-Max-Age response header to return when I go through the esp layer.  If I call the cloud function then I see the Access-Control-Max-Age properly, but when going through esp I getting warning messages saying it was not returned by the server.  Is there any way to get allowCors: true to allow this response header to pass through?

**Comment by qiwzhang** [comment]
ESP deployed in Cloud Run has to use x-google-backend to specify your backend server.  In such deployment,  allowCors: true doesn't work.  

Please see the detail https://github.com/cloudendpoints/esp/issues/737

**Comment by HN-JHOFF** [comment]
Not sure why this was closed so quickly, but your suggestion does not seem to solve my problem.  I rewrote the OpenAPI doc as you described... i.e. I removed the allow cors option and added an options path for each cloud function : 

options:
      summary: HN Auth Options
      operationId: hnauthoptions
      x-google-backend:
        address: {my address}
      responses:
        '204':
          description: Options Request

Just as before... I see most of the CORS traffic flowing... meaning my Access-Control-Allow-Methods, Access-Control-Allow-Credentials, and Access-Control-Allow-Origin settings all return properly.  Specifically, the Access-Control-Max-Age response header is being removed somewhere in the ESP layer.  Is there a way to get it to pass through?

Here is the response when going through the ESP : 

![Through ESP](https://user-images.githubusercontent.com/59065492/71265475-4c9e9200-2314-11ea-9dde-e74131f99f0d.jpg)

Here is a direct execution of the exact same Cloud Function : 

![Direct CF Invoke](https://user-images.githubusercontent.com/59065492/71265507-588a5400-2314-11ea-9cfd-dc96a90dc371.jpg)

**Comment by qiwzhang** [comment]
You suspect that ESP (or Nginx) is removing Access-Control-Max-Age response header

Let me investigate

**Comment by qiwzhang** [comment]
I research Nginx. It doesn't seem it touch Access-Control-Max-Age.   Look at your data, it seems that it is removed by "Google Frontend".  

My suspicious that: your backend is adding that header to regular HTTP response.  But Access-Control-Max-Age header is designed only for preflight OPTIONS request.  Maybe that is why Google Front end remove it. 

Could you verify if the response from your OPTIONS request have that header or not?

**Comment by HN-JHOFF** [comment]
Thanks for looking at this further.  In my architecture the "google frontend" is just a standard app engine that serves the initial angular SPA app download.  The two images I showed above are from instances where the app (which is then running fully on the client) makes angular httpclient post requests to my google hosted cloud functions.  To generate those images I simply changed the url for the post to be either the esp proxy or directly to the cloud functions, so I am not sure the google frontend would block in one scenario and not the other because it is the same calling app using the same google frontend in both cases.  The chrome developer tools don't show the options request and responses, so I will have to figure out how to capture that.  I can look into that further if it is helpful...

**Comment by HN-JHOFF** [comment]
OK, digging further, you are correct that the max age header should only be present on the options requests; however, I still have an issue though because the value I specify on the backend (600 in this case) is not what is being returned.  Here is the return of the options request in chrome : 

![204](https://user-images.githubusercontent.com/59065492/71295575-75417e80-234a-11ea-88c1-09b5710a2f5e.jpg)

1728000 appears to what chrome defaults to if the header is not returned.  Most browsers seem to mostly ignore this issue, but edge throws a warning with every single API call.

![browser](https://user-images.githubusercontent.com/59065492/71295619-bf2a6480-234a-11ea-8282-64032132f658.jpg)

The warnings stop when I call the cloud function directly and my specified 600 value is returned.  Any idea why this would get dropped or changed through the ESP layer?

**Comment by qiwzhang** [comment]
Then, I suspected that you are using CORS flags in ESP_ARGS.  That OPTIONS request is not handled by your backend function, is handled by ESP.   By default, ESP access-control-max-age is 1728000.  Here is the [code](https://github.com/cloudendpoints/esp/blob/master/start_esp/nginx-auto.conf.template#L179)

If you added OPTIONS in your OpenApi spec., you don't need to add and CORS flags to ESP by using ESP_ARGS.  

Please see the detail #737

**Comment by HN-JHOFF** [comment]
Per your initial response I removed the entire ESP arguments line.  When I last deployed I used just this command :  

            gcloud run deploy hncf-cloud-run \
            --image="gcr.io/{my project id}/endpoints-runtime-serverless:2019-12-04r0" \
            --allow-unauthenticated \
            --project={my project id}

Where I have replaced my actual project id with {my project id} here just so its not published.  I previously did have an additional line that said : 

--set-env-vars=ESP_ARGS=^++^--cors_preset=cors_with_regex++--cors_allow_origin_regex='^https://(www\.)?(hoffnorth.com)$'++--cors_allow_credentials++--cors_allow_methods='POST'++--cors_allow_headers='content-type' \

But that line is now removed completely.  Is there anywhere else I can check to see if ESP args are being used?  As far as I can tell I have removed them completely.....

**Comment by qiwzhang** [comment]
Did you set the cors flag in your docker image?  Because if your cors flags have ","  my document recommends to write these flags into the gcloud_build_image script, and built them into your docker image?

**Comment by HN-JHOFF** [comment]
I don't think so.  Here is the gcloud_build_image file.  I say no because I never changed this file, just downloaded the default and used it....

[gcloud_build_image.txt](https://github.com/cloudendpoints/esp/files/3990727/gcloud_build_image.txt)

Note I added the .txt entension here just so git would accept it....

**Comment by HN-JHOFF** [comment]
The only reason I am even using the ESP is because CFs don't support custom domains... so for me this is truly just a pass through...

**Comment by qiwzhang** [comment]
Well, in that case, could you check your Cloud Run and Cloud function log to see who handled the OPTIONS calls?

**Comment by HN-JHOFF** [comment]
Sure....  Fortunately not many users use edge, so my only edge usage today was the test I ran earlier.  Also fortunately, nothing else came in during that same minute, so if I look at cloud run I see the 204 and 4 subsequent 200s : 

![cloud run](https://user-images.githubusercontent.com/59065492/71300715-7b912400-2365-11ea-8435-ff640d3359b8.jpg)

If I look at the associated cloud function for the same minute I just see the 4 200s : 

![cloud functions](https://user-images.githubusercontent.com/59065492/71300731-8ea3f400-2365-11ea-890c-2cbf4b3e5c67.jpg)

Which seems to support your theory that cloud run is handling Options requests, but why?  I don't have any esp arguments, no longer have allowcors anywhere, and have specified the x-google-backend as prescribed?  Also, when I do change how I handle ANY of the other CORS headers in the cloud functions I see the expected result.  Is there something else that should be checked?

**Comment by qiwzhang** [comment]
Well, my only suspicious is you are running an old Cloud Run ESP service with the CORS flags. Maybe you can check your ESP service starts time.   or just re-deploy the Cloud Run ESP service.

**Comment by HN-JHOFF** [comment]
Thanks Wayne.  I tried a few things and couldn't ever get the existing service to work, but I did what you suggested and just started from scratch.  I built a completely new end point service and used the updated OpenAPI from the start and it is working as expected.  The header is now flowing and I see the 204s in the cloud function logs.  Not sure why I couldn't remove the CORS handling from an existing service, but you can consider this one closed.  I truly appreciate the knowledgeable assistance.
