### ISSUE TITLE
Add trace context headers when ESP starts a trace

### ISSUE THREAD

**Issue by farmdawgnation** [cloudendpoints/esp#740]
ESP will start a Cloud Trace for incoming requests on its own at certain intervals even if there's no incoming `X-Cloud-Trace-Context` or `grpc-trace-bin` header with the incoming request. We would like ESP to add a `X-Cloud-Trace-Context` header and/or a `grpc-trace-bin` header for the "Backend" span to the request to the backend when ESP creates traces so that our backends can use the ESP-started trace as a remote parent span.

**Comment by qiwzhang** [comment]
ESP should already do that.  If a trace is enabled, either by the trace context or by auto sampling, X-Cloud-Trace-Context is added to carry the span_id to send to the backend.

The code is [here](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/context/request_context.cc#L422)

**Comment by farmdawgnation** [comment]
Huh. I haven't been able to reproduce that behavior locally. My understanding is that if I sent less than one request every 10 seconds I should see the trace header when I send a request in my local environment. I'm happy to keep tinkering though. Certainly looks like it _should_ be doing that from what I can tell.

**Comment by farmdawgnation** [comment]
I figured out what was going on here - there was another request that my testing script was issuing automatically that was the first request ESP saw within 10 seconds so that one was getting traced instead of the one I intended. Thanks!
