### ISSUE TITLE
Memory leak in ESP 1.34?

### ISSUE THREAD

**Issue by ashi009** [cloudendpoints/esp#749]
We noticed this two days ago, under the normal load (GRPC-web and GRPC over HTTP/2, see fig 1) the memory usage of all ESPs for a single service surged from ~100MB to ~2GB in 4 hours (fig 2).

Fig 1
![image](https://user-images.githubusercontent.com/687367/71943157-a2bb7280-31fa-11ea-88e2-5b0c41983c40.png)

Fig 2
![image](https://user-images.githubusercontent.com/687367/71942797-59b6ee80-31f9-11ea-9fed-5733d794168a.png)

We have tried to reproduce this, but so far has no luck. 

As there is no mentioning of memory leak fix in recent releases, I assume this is not yet addressed.

**Comment by ashi009** [comment]
After taking a deeper look into this, the memory usage of ESP for all three tracks surged. And interestingly enough, the testing/qa tracks don't have any traffic at the time. So this event is not traffic triggered?

![image](https://user-images.githubusercontent.com/687367/71947853-1c5a5d00-3209-11ea-9ae9-857da91020a7.png)

**Comment by TAOXUY** [comment]
So, so far it is not reproduceable?

BTW, 1.34 is kind of old and you may try the latest version.

**Comment by qiwzhang** [comment]
Yeap,  1.34 is very old.  We have upgraded grpc since then.  We really like you to try the latest version.

**Comment by qiwzhang** [comment]
@ashi009 have you try to run the latest release? any update on the result?

**Comment by ashi009** [comment]
We are now running 1.45, and haven't seen a recurrence of this.

**Comment by qiwzhang** [comment]
ashi009, Thanks for the update.
