### ISSUE TITLE
Cloud Run: 500 INTERNAL ERROR for CORS requests

### ISSUE THREAD

**Issue by maroux** [cloudendpoints/esp#755]
I'm not sure what changed - I starting seeing 500 errors on 1.44:
```
→ curl -i hello.example.com/hello -XOPTIONS
HTTP/2 500 
content-type: application/json
date: Thu, 16 Jan 2020 18:10:05 GMT
server: Google Frontend
content-length: 185

{
 "code": 13,
 "message": "INTERNAL_SERVER_ERROR",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "application"
  }
 ]
}
```

I rolled back all the way to 1.40 and still see the same 500 error. Endpoints config has cors enabled:
```
x-google-endpoints:
- name: hello.example.com
  allowCors: true
```

Only see this error log in Cloud Run logs:
```
  textPayload: "2020/01/16 18:10:05 [error] 5#5: *3 invalid URL prefix in "", client: 136.25.38.10, server: hello.example.com, request: "OPTIONS /hello HTTP/1.1", host: "hello.example.com""  
```

It would seem this may happen if `backend_url` nginx var is empty - under what condition might that happen?

Tried enabling debug by adding `--enable_debug` but it didn't show anything extra that appears useful at first glance. 

Any ideas?

**Comment by qiwzhang** [comment]
Could it be the same issue as https://github.com/cloudendpoints/esp/issues/737?

**Comment by maroux** [comment]
Yes looks like the same bug @qiwzhang .. I searched for the error log `invalid URL prefix` and found no other references (other than the grpc ticket which isn't what I'm doing). I'll close this and comment there.
