### ISSUE TITLE
no updates with rollout_strategy=managed 

### ISSUE THREAD

**Issue by mrgleeco** [cloudendpoints/esp#757]
i preface with: i may be misunderstanding the nature of this flag `--rollout_strategy=managed`.
Is there a function within the running container that polls for the latest endpoints config version? Or do i need to restart the container to obtain a new latest config?

It is the case that i have everything working when i set up and run the container. However after a new endpoints config is put in to service (ie. `gcloud endpoints service deploy`), the container does not ever obtain it. No logging to indicate any activity of this nature either. 

Is there something obvious i've missed either about how this should work?

**Comment by qiwzhang** [comment]
If your service config is updated,  ESP should automatically get it and apply it with --rollout_strategy=managed.

You can check Stackdriver log in Cloud console to see if ESP is using the latest config_id.  Its jsonPayload looks like:

```
  api_method: "abc_method"   
  api_name: "abc_api"   
  api_version: "1.0.0"   
  client_ip: "10.24.1.93"   
  error_cause: "application"   
  http_method: "POST"   
  http_response_code: 400   
  location: "us-central1-f"   
  log_message: "Method:  abc_method  BAD_REQUEST"   
  request_latency_in_ms: 0   
  request_size_in_bytes: 939   
  response_size_in_bytes: 305   
  service_agent: "ESP/1.45.0"   
  service_config_id: "2020-02-04r0"   
```


If you look at ESP log (kubectl logs esp_container), you can see some log like
```
New rollout is deployed.
```
and other fetching info error too

The code is [here](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/api_manager_impl.cc#L141)
and 
[here](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/config_manager.cc)
