### ISSUE TITLE
RST_STREAM with error code 2 in GRPC requests

### ISSUE THREAD

**Issue by kball-humu** [cloudendpoints/esp#758]
I'm running into an issue where GRPC requests are failing with a message that looks like:

```
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Received RST_STREAM with error code 2"
        debug_error_string = "{"created":"@1580931046.068778000","description":"Error received from peer ipv4:35.241.15.148:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Received RST_STRE
AM with error code 2","grpc_status":13}
```

The setup is: I have the ESP in front of a grpc service. ESP is set up to terminate SSL, and then sends requests to the GRPC service. I'm able to successfully access via the json transcoding, so I'm pretty confident the backend service is working correctly. 

Stackdriver logs seem to indicate successful responses for both GRPC and JSON/HTTPS queries, but my client errors as seen above.

My `deployment.yaml` file is attached (though described as '.txt' because github wouldn't let me upload otherwise), as is `/var/log/nginx/error.log` from running with `--enable_debug` on. That file has 2 requests to the endpoint `/AquariumService/getMetadata`, the first done via GRPC (errored), the second with a json HTTPS post from postman.

Any direction about what to try or look into to understand what's failing would be appreciated.

[deployment.yaml.txt](https://github.com/cloudendpoints/esp/files/4161705/deployment.yaml.txt)

[error.log](https://github.com/cloudendpoints/esp/files/4161765/error.log)

**Comment by kball-humu** [comment]
I realized the problem might be the fact that the SSL is being terminated at ESP, so attempting to get ESP to talk to the backend grpc service over HTTPS... I had previously failed to get ESP to do this, but found undocumented flag `--enable_grpc_backend_ssl`

problem is I get a 'no match for server name: 127.0.0.1' because grpc service is using same certs and expecting the FQDN... is there a way to configure ESP to treat this as a proxy and pass that original requested ip/domain along?

**Comment by qiwzhang** [comment]
Since your grpc server is running side by side (in the same pod) with ESP, why do you need to use TLS?  Can you disable TLS in the grpc server?

**Comment by kball-humu** [comment]
I don't necessarily need to; I was originally trying to run the grpc server without TLS; just as I was looking for differences between the successful JSON based call and the unsuccessful GRPC call, one thing that stood out in the debug logs was the that the GRPC was highlighting it was insecure:

```
2020/02/05 19:41:51 [info] 9#9: *90 GrpcGetStub: Use insecure channel credentials, client: 50.239.249.146, server: , request: "POST /AquariumService/getMetadata HTTP/1.1", host: "dev-aquaserv.humu.com"
```

**Comment by kball-humu** [comment]
If I go back to no TLS, I'm back to prior state. Instrumenting the GRPC server, it believes it is returning the same data to both calls, but the JSON post from postman succeeds, while the python GRPC call fails with "Received RST_STREAM with error code 2"

**Comment by qiwzhang** [comment]
I will take a look your log.

**Comment by kball-humu** [comment]
I'm wondering if perhaps the service/ingress setup I have in front of the ESP is killing the http2 requests and translating them to http1... 

I only have the `ssl_port` configured and I've verified https queries are going through fine, but in the esp logs on the pod I see:

```
INFO:Fetching an access token from the metadata service
INFO:Fetching the service config ID from the rollouts service
INFO:Fetching the service configuration from the service management service
INFO:Attribute zone: us-central1-a
INFO:Attribute project_id: dev-squeegee-humu
INFO:Attribute kube_env: KUBE_ENV
nginx: [warn] Using trusted CA certificates file: /etc/nginx/trusted-ca-certificates.crt
50.239.249.146 - - [05/Feb/2020:20:42:38 +0000] "POST /AquariumService/getMetadata HTTP/1.1" 200 297 "-" "PostmanRuntime/7.22.0"
50.239.249.146 - - [05/Feb/2020:20:43:37 +0000] "POST /AquariumService/getMetadata HTTP/1.1" 200 245 "-" "grpc-python/1.26.0 grpc-c/9.0.0 (osx; chttp2; gon)"
50.239.249.146 - - [05/Feb/2020:21:13:11 +0000] "POST /AquariumService/getMetadata HTTP/1.1" 200 245 "-" "grpc-python/1.26.0 grpc-c/9.0.0 (osx; chttp2; gon)"
```

Which appears to be using HTTP/1.1 rather than the expected HTTP/2

Am I correct to expect those log lines to indicate HTTP2?

**Comment by kball-humu** [comment]
AH! That was it! Going to close this, that turned out to be the problem, nothing in ESP.

Thank you for your help and looking into it @qiwzhang
