### ISSUE TITLE
upstream request timeout

### ISSUE THREAD

**Issue by QuadTriangle** [cloudendpoints/esp#759]
I am getting `upstream request timeout` after 16 seconds.

I have followed https://medium.com/google-cloud/73c57bededd1 to enable API key in the Cloud Run service.

The Cloud Run API call can take a few minutes. but this endpoint is getting timeout after 16 seconds (original one works fine). APIs with shorter request time works fine with this endpoint.

**Comment by QuadTriangle** [comment]
major version 1 fixes the problem

**Comment by qiwzhang** [comment]
For ESPv2,  for long live request, you need to increase request "deadline" in x-google-backend as described [here](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#deadline).  The default is 15 second.  

For ESPv1,  default is described [here](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) and can be changed by a flag [here](https://github.com/cloudendpoints/esp/blob/d258b67d560df11c4a73d5acdc6c809048292a0a/start_esp/start_esp.py#L647)

**Comment by jason-leeee** [comment]
> 
> 
> For ESPv2, for long live request, you need to increase request "deadline" in x-google-backend as described [here](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions#deadline). The default is 15 second.
> 
> For ESPv1, default is described [here](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout) and can be changed by a flag [here](https://github.com/cloudendpoints/esp/blob/d258b67d560df11c4a73d5acdc6c809048292a0a/start_esp/start_esp.py#L647)

saved my day! thanks
