### ISSUE TITLE
Suspicious upstream timeout and super high latencies recorded in cloud trace

### ISSUE THREAD

**Issue by ashi009** [cloudendpoints/esp#768]
We are seeing request latencies for some requests are as high as 1000s, which normally << 1s, yet there are no changes made to the backend, and we can confirm that the requests in question never reach the backend from the logs.

![image](https://user-images.githubusercontent.com/687367/76394797-03109100-63b1-11ea-8e72-46b982da7993.png)

There is not much to dig from the ESP logs, except the "upstream timeout" messages.

We are using ESP 1.45 on GKE. The ESP and the backend are in different containers of the same pod, and ESP connects to the backend with the loopback interface.

Any pointers?

**Comment by qiwzhang** [comment]
From the graph,  it seems that your backend is not gRPC.  For http, ESP is using Nginx upstream to talk to the backend.  You can try to google Nginx upstream big latency to see if you can find any clues.  It could be GKE network related, try to search GKE latency issue.

**Comment by ashi009** [comment]
Our backend is grpc and we haven't seen new traces in the last 12 hours. No matter what caused this, it's gone.

**Comment by qiwzhang** [comment]
If it is grpc, we are calling grpc c++ client library by using its Channel.
