### ISSUE TITLE
Brotli Support through NGINX

### ISSUE THREAD

**Issue by ilyaGurevich** [cloudendpoints/esp#780]
Does the current version of ESP support a brotli compression through nginx at this moment in time? There is a brotli filter available here https://github.com/cloudendpoints/esp/blob/8a6138e7c2f442f21b4322c21c86f851fd252d37/src/nginx/main/ngx_modules.c#L218 -- but does it require a custom nginx module to be built, or is this already included in the latest version of ESP?

**Comment by qiwzhang** [comment]
Sorry, there was a typo in my previous message, I just corrected it.  It is NOT in the ESP nginx binary.

No, we don't have plan to add it.

**Comment by ilyaGurevich** [comment]
@qiwzhang do you have an example of how to hook up a docker instance with the nginx.conf using brotli?

**Comment by qiwzhang** [comment]
Sorry, I don't have any example on how to config brotfli compression in nginx config. 
Here is the [document](https://cloud.google.com/endpoints/docs/openapi/custom-nginx) on how to use custom nginx config in GKE.

**Comment by ilyaGurevich** [comment]
> No, we don't have plan to add it.

@qiwzhang sorry I deleted my previous message the one you responded to since I assumed it wasn't possible, however an alternative question -- if I put in the work to add the brotli configuration to this repo by opening a PR would it be something you would accept? Or by not planning to add it meaning your team won't do it, or it's just not something you want in here entirely?

**Comment by qiwzhang** [comment]
No means we don't have resource to do it.  If you can contribute, we will like to get it in.

**Comment by ilyaGurevich** [comment]
Sounds great! Will open a PR when possible

**Comment by ilyaGurevich** [comment]
@qiwzhang PR opened here: https://github.com/cloudendpoints/esp/pull/784

**Comment by ilyaGurevich** [comment]
Thank you @qiwzhang for merging the PR - how soon can a release occur?

**Comment by qiwzhang** [comment]
You just missed this week release.  Next release will be in 1 or 2 weeks.

**Comment by ilyaGurevich** [comment]
@qiwzhang understood -- whenever a release occurs this issue can be closed. Thanks!
