### ISSUE TITLE
incorrect parsing of URL query string with %20 (space)

### ISSUE THREAD

**Issue by toby-1-kenobi** [cloudendpoints/esp#799]
when a value is passed in the query using a URL query string and it includes a space ('%20' in the URL) then instead of it being decoded as a space character for the protobuf message it is decoded as a plus character ('+')

As a result all of these three strings from a URL decode to the same string in the protobuf: "a+b"
a+b
a%20b
a%2Bb

(as a side issue, I'm not sure about whether a '+' in the URL should also decode to a space. I suppose there could be arguments either way for that, but I personally prefer that it does become a space)

**Comment by qiwzhang** [comment]
Hmm,  I just checked the [code](https://github.com/cloudendpoints/esp/blob/master/src/api_manager/path_matcher.h#L313), it should not happen.

**Comment by qiwzhang** [comment]
We also have a "t" test to cover this.  Here is the [test](https://github.com/cloudendpoints/esp/blob/master/src/nginx/t/transcoding_query_params.t#L139) with escaped chars.

**Comment by toby-1-kenobi** [comment]
OK then. It must be something else in my own setup that's causing this.

**Comment by toby-1-kenobi** [comment]
I'm running it locally like this:
sudo docker run \
    --detach \
    --name="esp" \
    --net="host" \
    --volume=$HOME/Downloads:/esp \
    --publish=8082 \
    gcr.io/endpoints-release/endpoints-runtime:1.45 \
    --service=rev79.endpoints.rev79-232812.cloud.goog \
    --rollout_strategy=managed \
    --http_port=8082 \
    --backend=grpc://localhost:3011 \
    --service_account_key=/esp/service-account-creds.json

**Comment by qiwzhang** [comment]
could you add --enable_debug in the ESP flag, just like  --http_port?

From inside the ESP container,  locate /etc/log/nginx/error.log to find out the request received by ESP,  get its URL with query parameters. 

Unfortunately, we don't have debug log after transcoding,   you either can get it from your backend grpc server,  or you may have to get it from tcpdump.
