### ISSUE TITLE
Auto-generated SmartDocs / dev portal convert API to camel case incorrectly

### ISSUE THREAD

**Issue by jschultz410** [cloudendpoints/esp#802]
I'm using google cloud endpoints with ESP to deploy a gRPC service with a REST transcoded API exposed as well.  

I'd like to use the auto-generated documentation from the .proto's, but the documentation auto-converts both the REST and gRPC field names to use CamelCase rather than preserving the original snake_case, which is what both APIs actually use.

https://cloud.google.com/endpoints/docs/grpc/dev-portal-overview

I figured out how to make ESP transcoding preserve the camel case using the --transcoding_preserve_proto_field_names parameter, but how do I do the same for the auto-generated documentation?  And why is converting my gRPC documentation in the first place?

I also asked a similar question on stackoverflow with a bounty if you want some reputation:

https://stackoverflow.com/questions/62031147/configuring-smartdocs

**Comment by qiwzhang** [comment]
It seems that you are talking about Endpoint Portal,  how to preserve proto field names in its doc,  is that correct?

**Comment by qiwzhang** [comment]
@wyrickre  do you know who can help?

**Comment by jschultz410** [comment]
> It seems that you are talking about Endpoint Portal, how to preserve proto field names in its doc, is that correct?

@qiwzhang Yes, I think that is correct.

**Comment by wyrickre** [comment]
I asked @AlanPeters to take a look...

**Comment by AlanPeters** [comment]
The Cloud Endpoints Portal creates HTTP documentation to supplement the gRPC documentation for any method with a google.api.http annotation. 

Currently the portal only supports generating the documentation with field names converted to camel case. I will create an issue to look into changing this to support both in the future.

**Comment by jschultz410** [comment]
@AlanPeters Thanks!  Just to be clear, it wasn't just the HTTP documentation -- the gRPC documentation is also converting my field names to use CamelCase too for some reason, which was surprising.

**Comment by AlanPeters** [comment]
Thanks for clarifying. Both the gRPC documentation and the HTTP docs are generated directly from the proto files and does not currently know about the --transcoding_preserve_proto_field_names parameter

**Comment by jschultz410** [comment]
@qiwzhang What was the resolution of this issue?

**Comment by qiwzhang** [comment]
This is not the right place for this issue.  That is why I close it.   Could you check with @AlanPeters to find a proper place to file the issue?
