### ISSUE TITLE
ESP fails to connect to google service

### ISSUE THREAD

**Issue by VikasAppani** [cloudendpoints/esp#807]
@qiwzhang @nareddyt 

Deployed cloud endpoints on top of backend application running on gke. 
I get the below error while hitting the endpoints : 
]
{

    "code": 16,
    "message": "JWT validation failed: Unable to fetch verification key",
    "details": [
        {
            "@type": "type.googleapis.com/google.rpc.DebugInfo",
            "stackEntries": [],
            "detail": "auth"
        }
    ]
}

**logs from my pod** : 2020/07/08 18:32:19 [error] 9#9: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2020/07/08 18:32:36 [error] 9#9: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2020/07/08 18:32:36 [error] 9#9: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2020/07/08 18:32:36 [error] 9#9: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2020/07/08 18:32:49 [error] 9#9: servicecontrol.googleapis.com could not be resolved (110: Operation timed out)
2020/07/08 18:32:49[error]9#9: Failed to call https://servicecontrol.googleapis.com/v1/services/xxxx.endpoints.default.cloud.goog:report, Error: ERROR: Failed to connect to server., Response body: 
[libprotobuf ERROR external/servicecontrol_client_git/src/service_control_client_impl.cc:182] Failed in Report call: Failed to connect to service control

**Comment by qiwzhang** [comment]
It seems that your GKE cluster has network connectivity problem.  It could not connect to external services.  The auth error means ESP could not connect to the jwks_uri, the public key server for JWT auth.   The error log indicate DNS could not resolve servicecontrol.googleapis.com.  The default DNS resolver is 8.8.8.8,  it means your cluster could not connect to it.

Could you verify that your cluster has external network connection?   Please verify it can connect to jwks_uri that you specified in security section of openapi spec.  Please also verify it can connect to 8.8.8.8.  If not,  can it connect to metadata server 169.254.169.254?  

One think you can try is to use 169.254.169.254 as your DNS resolver by specify flag --dns=169.254.169.254
