### ISSUE TITLE
GRPC keepalive server side not working

### ISSUE THREAD

**Issue by unludo** [cloudendpoints/esp#812]
Esp is in front of a grpc server inside a gke pod.
The grpc server is sending keepalive messages.
A client connects to the grpc endpoint, via esp, to grpc server.

Physical disconnection between client and server happens.
Nothing is detected by the grpc server.

If esp is removed and client connects directly to the grpc server, then the latter detect the disconnection.

Is there a special configuration to have esp to 'correctly' manage keepalive messages from server? Currently it seems (in the sense that it is just a supposition) that esp responds to the keepalive messages itself and does not relay them to the client.

**Comment by qiwzhang** [comment]
ESP downstream and upstream are using different connections.  There is not one to one connection mapping between these two,  it only has stream to stream mapping.   upstream is using grpc channel,  many downstream connections may use one grpc channel.  So mapping keep alive between downstream and upstream is difficult.

**Comment by unludo** [comment]
@qiwzhang Thank you for your answer. I don't understand though as each stream is specific to each client - server connection. There is 'broadcast'.

I was wondering, is it possible to have a grpc client to communicate with a grpc server through a L4 LB without an ESP?
ESP is doing grpc proxy or more ?
I tried to not use an ESP but was not able to have Client -> L4 LB -> Server (inside GKE) working, whereas with Cleint -> L4 LB -> ESP + server it works. Is it normal for you?

**Comment by qiwzhang** [comment]
In theory,  L4LB should work for gRPC protocol.  
It may have something to do with your GKE LB or Ingress that doesn't support Http2.  ESP can convert http1 to http2.  But I believe GKE LB or Ingress does support http2, you may have configured it wrong.

**Comment by unludo** [comment]
Actually I use L4 LB which is tcp. I have no ingress.
________________________________

**Comment by qiwzhang** [comment]
Somewhere in the path-path,  grpc request is downgraded from http2 to http1, and ESP upgrades back to http2.  That is how ESP has helped.
