### ISSUE TITLE
pass zero from grpc to json

### ISSUE THREAD

**Issue by nosovk** [cloudendpoints/esp#815]
Currently there is no way to implement json output with zero value, like:
```json
{"id": 35, "rating":0}
```
always will be transformed to
```json
{"id": 35}
```
removing 0 fields from response.
It's ok for grpc, but for frontend world its bit obvious that in our api missing fields are zero. Is there any way to pass 0 via ESP?

**Comment by qiwzhang** [comment]
You can add this [flag](https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L755) 
--transcoding_always_print_primitive_fields

**Comment by nosovk** [comment]
great, it solved my issue. Thanks.
