### ISSUE TITLE
ESP on Compute Engine : JWT validation failed: Unable to fetch verification key

### ISSUE THREAD

**Issue by eshwarprasadhu** [cloudendpoints/esp#817]
Hi,
I’m running an ESP docker container on Compute Engine VM. When I’m accessing the api it's giving this error message ("JWT validation failed: Unable to fetch verification key")

The api does work when I allow all egress traffic. The expectation is the api should work with default deny egress firewall in-place

Please note that I had enabled the below listed access
1. Allowed egress traffic to the IP addresses of private.googleapis.com 
2. Created private google access route
3. Service Account private key json is included in the esp container

The esp container log shows connection timed out error. 

```
2020/09/23 12:06:54[error]9#9: Failed to call https://servicecontrol.googleapis.com/v1/services/<myservice>:report, Error: ERROR: Failed to connect to server., Response body:
2020/09/23 12:07:02 [error] 9#9: upstream timed out (110: Connection timed out)
2020/09/23 12:07:06 [error] 9#9: upstream timed out (110: Connection timed out)
```

**Comment by qiwzhang** [comment]
You are reporting two issues:
1) failed to fetch JWKS: jwt public keys,  the url is specified in x-google-jwks_url  in openapi spec.
2) failed to connect to Google API, e.g. Google service control API

Unless x-google-jwks_uri specified a Google API,  they are two different problems; accessing Google API may require different configuration than accessing other remote endpoints.

for 1),  I think your egress need to allow to access that jwks_uri.  
for 2), It seems that Google service control is still not allowed. report call is rejected.

You may have to check your egress settings to allow jwks_uri and Google API.

**Comment by eshwarprasadhu** [comment]
for 1) - I have this url `https://www.googleapis.com/robot/v1/metadata/x509/<service_account>` as `x-google-jwks-uri` in openapi spec. 
for 2) - The Google Service Control API also has the domain ending with *.googleapis.com 

The url 1) & 2) is translating into an IP address that is in the IP range `199.36.153.8/30`
![image](https://user-images.githubusercontent.com/51907579/94099324-58415b00-fe48-11ea-9ad5-a26811863b54.png)

![image](https://user-images.githubusercontent.com/51907579/94099362-6c855800-fe48-11ea-875b-da7cdd95bc2b.png)

The connectivity from host VM is fine. Verified the same by doing a telnet. 

![image](https://user-images.githubusercontent.com/51907579/94100119-642e1c80-fe4a-11ea-9c93-dcde8d891ceb.png)

![image](https://user-images.githubusercontent.com/51907579/94100139-70b27500-fe4a-11ea-81cb-c85d5e08cea8.png)

Please refer the below screenshot, I have allowed egress to the same IP range in my firewall settings. 

![image](https://user-images.githubusercontent.com/51907579/94098813-1b289900-fe47-11ea-9ca8-a813c9079eb8.png)

Not sure what is going wrong here. Please advise.

**Comment by qiwzhang** [comment]
Hmm,  you may be using private VPC.  or your GCE VM only has internal IP address.  If so, you need to follow some special setup to access Google services.  

I am not expert in this area.  I just happened to read this [doc](https://cloud.google.com/vpc/docs/private-access-options#pga-supported).   You may need to find some help from other Google supports.

**Comment by nareddyt** [comment]
I'm not convinced about your IP range `199.36.153.8/30`. Are you forming this based on your own observations? Here is the IP address I get from my local machine.

```
nareddyt-macbookpro% ping servicecontrol.googleapis.com
PING servicecontrol.googleapis.com (172.217.0.42): 56 data bytes
```

As Wayne said, this seems to be out of scope for us, we are not experts in this.

**Comment by eshwarprasadhu** [comment]
@nareddyt  It's as per gcp documentation. Please refer this link [Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access#config)

**Comment by eshwarprasadhu** [comment]
@qiwzhang  Yes, We are using private VPC and we don't use external address for our GCE VM.

**Comment by eshwarprasadhu** [comment]
@qiwzhang It looks like a bug in connectivity between google service apis managing the endpoints. Please direct to the support team who can help in this regard

**Comment by qiwzhang** [comment]
Could you post your evidence here so that I can create a external bug for you?  Or you can create a bug for GCP youself?

**Comment by eshwarprasadhu** [comment]
I filed a bug for GCP Cloud APIs. Link for your reference https://issuetracker.google.com/issues/169349072

**Comment by eshwarprasadhu** [comment]
The problem got resolved by overriding ESP container's default DNS Resolver (8.8.8.8) with the correct DNS Resolver

**Comment by qiwzhang** [comment]
That make sense.  For a GCE with private IP,  it has to use GCP metadata server as DNS resolver.
