### ISSUE TITLE
HTTP Post x-www-form-urlencoded transcoding

### ISSUE THREAD

**Issue by BulatMukhutdinov** [cloudendpoints/esp#821]
I am using http transcoding as follows
```
rpc SpotifyIosAuth (SpotifyIosAuthRequest) returns (SpotifyIosAuthResponse) {
    option (google.api.http) = {
      post: "/spotify/ios/swap"
      body: "iosAuthCode"
    };
  };

message SpotifyIosAuthRequest {
  SpotifyIosAuthCode iosAuthCode = 1;
}

message SpotifyIosAuthCode {
  string code = 1;
}
```

When I call ```curl -d '{"code":"myCode"}' localhost:81/spotify/ios/swap```
ESP prints 400 code (for all grpc requests it prints 200) and my backend service doesn't receive a call. 
Is there any way to print full body logs for http requsts?

**Comment by qiwzhang** [comment]
Are you using ESPv1 or ESPv2?  Since you open the issue in this repo,  I assume you use ESPv1.   

In ESPv1,  Http port is different with grpc port ( or http2 port) unless you use ssl.   You have to specify [http2_port](https://github.com/cloudendpoints/esp/blob/master/start_esp/start_esp.py#L536) and http_port,

**Comment by BulatMukhutdinov** [comment]
Yes, I am using ESPv1. Here are my configs
api_config.yaml
```type: google.api.Service
config_version: 3

#
# Name of the service configuration.
#
name: xxx.endpoints.xxx.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: gRPC API

apis:
  - name: spotify.SpotifyAuthService

#
# API usage restrictions.
#
usage:
  rules:
    # Allow unregistered calls for all methods.
    - selector: "*"
      allow_unregistered_calls: true
```

ESP docker config
```
sudo docker run \
    --publish=80:9000 \
    --publish=81:8082 \
    --net=esp_net \
    --name=esp \
    gcr.io/endpoints-release/endpoints-runtime:1 \
    --service=xxx.endpoints.xxx.cloud.goog \
    --rollout_strategy=managed \
    --http2_port=9000 \
    --http_port=8082 \
    --client_body_timeout=100d \
    --backend=grpc://backend:50051
```

backend config
```
sudo docker run \
    --net=esp_net \
    --name=backend \
    --publish=50051:50051 \
    gcr.io/xxx/xxx-image:1.3
```

ESP response for HTTP1 request
```
[13/Nov/2020:18:47:27 +0000] "POST /spotify/ios/swap HTTP/1.1" 400 213 "-" "XXX/1 CFNetwork/1128.0.1 Darwin/19.6.0"
```

Could you tell me please, is there any way to see logs about for rest requests and responses?

**Comment by BulatMukhutdinov** [comment]
One more detail: if I call my http1 method from curl like ```curl -d '{"code":"myCode"}' localhost:81/spotify/ios/swap``` then response from esp still 400, but it redirects request to my backend. But when I call this method from iPhone it prints 400 code and doesn't redirect the call to my backend

**Comment by BulatMukhutdinov** [comment]
I found that exception is intercept by ```ServerInterceptor```. The exception description is ```Expected one request for ... but received none```

**Comment by BulatMukhutdinov** [comment]
I think I found the case - request uses ```x-www-form-urlencoded``` body. Is there any way to explicitly set is in the transcoding section?

**Comment by qiwzhang** [comment]
Unfortunately, ESP doesn't support request body from x-www-form-urlencoded.  Body has to be in JSON format.

Let us try to narrow down the JSON problem.
1) try to use `curl` in the same machine as ESP.   
2) you can add --enable_debug in the ESP start up flags.  The debug log is inside the ESP container in its /etc/log/nginx.
