### ISSUE TITLE
Malformed WWW-Authenticate header payload returned for UNAUTHORIZED response

### ISSUE THREAD

**Issue by awalls-cx18** [cloudendpoints/esp#843]
When a backend server returns an `grpc.StatusCode.UNAUTHENTICATED` (aka "401 Unauthorized") ESP injects a malformed `www-authenticate: Bearer, error="invalid_token"` response header that is not RFC compliant.

In the returned challenge, there should not be a comma, `,`, between the authentication scheme, `Bearer`, and the first authentication parameter `error="invalid_token"`.

Please remove the comma, so that the injected header is `www-authenticate: Bearer  error="invalid_token"`.

https://datatracker.ietf.org/doc/html/rfc7235#section-4.1
https://datatracker.ietf.org/doc/html/rfc7235#appendix-C
https://datatracker.ietf.org/doc/html/rfc6750#section-3 (examples at the end of this section)

https://github.com/cloudendpoints/esp/blob/master/src/nginx/error.cc#L53
https://github.com/cloudendpoints/esp/blob/master/src/nginx/error.cc#L86

**Comment by awalls-cx18** [comment]
FWIW, You could also just insert a space between the `Bearer` and the `,` and be RFC compliant, indicating an empty first authentication parameter in the list of authentication parameters, but it wouldn't make much sense and could trip up `www-authenticate` header parsing implementations that are not careful.

**Comment by qiwzhang** [comment]
This is not the new behaviors.  This is the way since day 1.   Unfortunately,  ESPv1 is in the maintaining mode to support existing users with existing features.  This must be a new usage.  We recommend you to switch to [ESPv2](https://cloud.google.com/endpoints/docs/openapi/migrate-to-esp-v2).

**Comment by awalls-cx18** [comment]
We've been using ESPv1 for a couple of years. This just came up because we've added some multi-factor authentication that is handled by our backend.  We've already adapted our browser resident code to deal with the non-conformance.

Knowing that it is never going to be fixed is fine.  Closing.
